import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "MCP setup · Dialogue Lab", description: "Connect Dialogue Lab to Codex or Claude Code." };

export default function McpSetupPage() {
  return <main className="docs-page">
    <nav className="docs-nav"><Link href="/docs">← All guides</Link><span>MCP setup</span></nav>
    <header className="docs-hero"><p>Dialogue Lab + AI agent</p><h1>Connect the MCP server</h1><span>Give Codex or Claude Code direct access to your local Dialogue Lab projects, voices, characters, timelines, captions, media, and render queue.</span><div className="docs-recommendation"><strong>Highly recommended</strong><p>Keep Dialogue Lab open for visual preview and precise manual adjustments while your agent authors and revises the same projects through MCP.</p></div></header>
    <div className="docs-layout">
      <aside><a href="#prepare">Before connecting</a><a href="#codex">Codex</a><a href="#claude">Claude Code</a><a href="#source">Source checkout</a><a href="#verify">Verify</a><a href="#workflow">Workflow</a><a href="#troubleshooting">Troubleshooting</a></aside>
      <article>
        <section id="prepare"><h2>Before connecting</h2><ol><li>Install Node.js 22.13 or newer.</li><li>Install FFmpeg and ffprobe on <code>PATH</code>.</li><li>Open Dialogue Lab and connect a voice provider.</li><li>Add at least one voice and character.</li></ol><p>The provider key belongs in Dialogue Lab, not in your MCP configuration or agent prompt.</p></section>
        <section id="codex"><h2>Codex</h2><p>After the package is published, run:</p><h3>macOS or Linux</h3><pre><code>codex mcp add dialoguelab -- npx -y dialoguelab-mcp</code></pre><h3>Windows</h3><pre><code>codex mcp add dialoguelab -- cmd.exe /d /c npx.cmd -y dialoguelab-mcp</code></pre><p>Run <code>codex mcp list</code>, restart the current Codex client, and use <code>/mcp</code> to inspect the connection. Codex Desktop, CLI, and IDE clients share the host's MCP configuration. See the <a href="https://developers.openai.com/codex/mcp" target="_blank" rel="noreferrer">official Codex MCP documentation</a>.</p></section>
        <section id="claude"><h2>Claude Code</h2><h3>macOS or Linux</h3><pre><code>claude mcp add --transport stdio --scope user dialoguelab -- npx -y dialoguelab-mcp</code></pre><h3>Windows</h3><pre><code>claude mcp add --transport stdio --scope user dialoguelab -- cmd.exe /d /c npx.cmd -y dialoguelab-mcp</code></pre><p>Run <code>claude mcp list</code>, start or restart Claude Code, and use <code>/mcp</code> in the session. User scope makes Dialogue Lab available across your projects. See the <a href="https://code.claude.com/docs/en/mcp" target="_blank" rel="noreferrer">official Claude Code MCP documentation</a>.</p></section>
        <section id="source"><h2>Connect a source checkout</h2><p>Before the npm package is published, build the local executable:</p><pre><code>npm ci{`\n`}npm run build:mcp</code></pre><p>Replace the <code>npx -y dialoguelab-mcp</code> part of the command above with:</p><pre><code>node /absolute/path/to/dialoguelab/packages/dialoguelab-mcp/dist/cli.js</code></pre><p>Use a Windows absolute path on Windows. Rebuild after changing MCP or server code.</p></section>
        <section id="verify"><h2>Verify the connection</h2><p>After restarting the client, ask:</p><pre><code>Use the Dialogue Lab MCP server. Call get_app_status, then list_projects.</code></pre><p>Next, try a read-only inspection:</p><pre><code>Inspect my Dialogue Lab voices, characters, and backgrounds. Do not change anything yet.</code></pre><p>The server automatically shares Dialogue Lab's normal private app-data directory. If you set <code>DIALOGUELAB_DATA_DIR</code> manually, use the same absolute path for the app and MCP process.</p></section>
        <section id="workflow"><h2>Recommended combined workflow</h2><ol><li>Curate providers, voices, characters, poses, and backgrounds in the app.</li><li>Ask Codex or Claude Code to inspect those libraries.</li><li>Have the agent propose and author dialogue, then generate missing speech.</li><li>Review the synchronized result visually in Dialogue Lab.</li><li>Adjust manually or describe revisions to the agent.</li><li>Ask the agent to validate and render the project.</li></ol><p>Both interfaces use the same revision history, and revision checks protect newer UI edits from being silently overwritten.</p></section>
        <section id="troubleshooting"><h2>Troubleshooting</h2><ul><li>If the server is absent, run the client's MCP list command and restart the session.</li><li>On Windows, use <code>cmd.exe /d /c npx.cmd</code> for the npm package.</li><li>For source checkouts, rerun <code>npm run build:mcp</code>.</li><li>If projects are missing, check for mismatched <code>DIALOGUELAB_DATA_DIR</code> values.</li><li>If speech fails, reconnect a provider in Dialogue Lab Settings.</li><li>If rendering fails, verify FFmpeg with <code>npm run doctor</code>.</li></ul><p>Repository users can run <code>npm run verify:package-mcp</code> to test the packed server in a clean temporary installation.</p></section>
      </article>
    </div>
  </main>;
}
