"use client";

import { ArrowDown, ArrowLeft, ArrowUp, Captions, Check, Copy, Film, GripVertical, Image as ImageIcon, Layers3, LoaderCircle, Mic2, Pause, Play, Plus, Redo2, Settings2, SlidersHorizontal, Sparkles, Trash2, TriangleAlert, Type, Undo2, Upload, Users } from "lucide-react";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { BackgroundRecord, CharacterRecord, DialogueLineData, ProjectClipMotion, ProjectCommand, ProjectCommandResult, ProjectEditorState, ProjectElementTransform, ProjectMediaAssetRecord, ProjectRecord, ProjectRenderJobRecord, RedditPostData, RenderQuality, SpeechClipRecord, VoiceRecord } from "@/shared/contracts";
import { compileDialogueTimeline, DEFAULT_PROJECT_TRANSFORM, defaultDialogueCharacterTransform, dialogueBlocks, normalizeProjectMotion } from "@/shared/project-timeline";
import { motionPresetName } from "@/shared/motion-catalog";
import { DialogueApiError, dialogueApi } from "@/lib/client-api";
import { HyperframesPreview, type ProjectPlayerAdapter } from "./HyperframesPreview";
import { SubtitleStylePanel } from "./SubtitleStylePanel";
import { CaptionWordEditor } from "./CaptionWordEditor";
import type { TimelineElementEdit, TimelineEditTarget } from "./StudioProjectTimeline";
import { AudioGenerationProgressDialog, type AudioGenerationTask } from "./AudioGenerationProgressDialog";
import { RenderHistoryDialog } from "./RenderHistoryDialog";
import { AnimationPickerDialog, type AnimationApplyScope, type AnimationPickerSubject } from "./AnimationPickerDialog";
import { FakeTextWorkspace } from "./FakeTextWorkspace";

const StudioProjectTimeline = dynamic(() => import("./StudioProjectTimeline").then((module) => module.StudioProjectTimeline), {
  ssr: false,
  loading: () => <div className="studio-timeline-loading">Loading HyperFrames Studio timeline…</div>,
});

type EditorTab = "characters" | "background" | "media" | "script" | "subtitles" | "inspector";

export function ProjectWorkspace(props: { project: ProjectRecord; onBack: () => void; onChanged: (project: ProjectRecord) => void }) {
  return props.project.editorState.projectType === "fake-text" ? <FakeTextWorkspace {...props} /> : <DialogueProjectWorkspace {...props} />;
}

function DialogueProjectWorkspace({ project: initialProject, onBack, onChanged }: { project: ProjectRecord; onBack: () => void; onChanged: (project: ProjectRecord) => void }) {
  const [project, setProject] = useState(initialProject); const projectRef = useRef(initialProject); const commandQueue = useRef<Promise<unknown>>(Promise.resolve());
  const [characters, setCharacters] = useState<CharacterRecord[]>([]); const [voices, setVoices] = useState<VoiceRecord[]>([]); const [backgrounds, setBackgrounds] = useState<BackgroundRecord[]>([]); const [media, setMedia] = useState<ProjectMediaAssetRecord[]>([]); const [speech, setSpeech] = useState<SpeechClipRecord[]>([]); const speechRef = useRef<SpeechClipRecord[]>([]); const [assetsLoading, setAssetsLoading] = useState(true);
  const [tab, setTab] = useState<EditorTab>("script"); const [saving, setSaving] = useState(false); const [generating, setGenerating] = useState<string>(); const [renderBusy, setRenderBusy] = useState(false); const [renderJobs, setRenderJobs] = useState<ProjectRenderJobRecord[]>([]); const [renderDialog, setRenderDialog] = useState(false); const [renderError, setRenderError] = useState<string>(); const [error, setError] = useState<string>();
  const [audioBatch, setAudioBatch] = useState<AudioGenerationTask[]>(); const [audioBatchRunning, setAudioBatchRunning] = useState(false); const stopAudioBatch = useRef(false);
  const [selectedTarget, setSelectedTarget] = useState<TimelineEditTarget>(); const [animationTarget, setAnimationTarget] = useState<TimelineEditTarget>(); const [currentTime, setCurrentTime] = useState(0); const [playing, setPlaying] = useState(false); const player = useRef<ProjectPlayerAdapter | undefined>(undefined);

  useEffect(() => { setProject(initialProject); projectRef.current = initialProject; }, [initialProject.id]);
  useEffect(() => {
    let cancelled = false; setAssetsLoading(true);
    void Promise.all([dialogueApi.characters.list(), dialogueApi.voices.list(), dialogueApi.backgrounds.list(), dialogueApi.media.list(), dialogueApi.speech.list()]).then(([nextCharacters, nextVoices, nextBackgrounds, nextMedia, nextSpeech]) => {
      if (cancelled) return; setCharacters(nextCharacters); setVoices(nextVoices); setBackgrounds(nextBackgrounds); setMedia(nextMedia); setSpeech(nextSpeech); speechRef.current = nextSpeech;
    }).catch((cause) => { if (!cancelled) setError(readError(cause)); }).finally(() => { if (!cancelled) setAssetsLoading(false); });
    return () => { cancelled = true; };
  }, []);
  const refreshRenders = useCallback(async () => setRenderJobs(await dialogueApi.projects.renders(projectRef.current.id)), []);
  useEffect(() => { void refreshRenders().catch((cause) => setRenderError(readError(cause))); }, [initialProject.id, refreshRenders]);
  useEffect(() => { if (!renderJobs.some((job) => ["queued","preparing","rendering"].includes(job.status))) return; const timer = window.setInterval(() => void refreshRenders().catch((cause) => setRenderError(readError(cause))), 900); return () => window.clearInterval(timer); }, [renderJobs, refreshRenders]);
  const selectedBackground = backgrounds.find((item) => item.id === project.editorState.assets.backgroundId);
  const compiled = useMemo(() => compileDialogueTimeline(project.editorState, speech, selectedBackground?.durationSeconds), [project.editorState, speech, selectedBackground?.durationSeconds]);
  const lines = dialogueBlocks(project.editorState); const readyLines = compiled.segments.filter((segment) => segment.speech).length;
  const selectedLineId = selectedTarget?.kind === "dialogue" ? selectedTarget.lineId : undefined;

  const acceptResult = useCallback((result: ProjectCommandResult) => { projectRef.current = result.project; setProject(result.project); onChanged(result.project); setError(undefined); return result; }, [onChanged]);
  const execute = useCallback((commands: ProjectCommand[], summary?: string) => {
    setSaving(true); const operation = commandQueue.current.catch(() => undefined).then(async () => {
      try { return acceptResult(await dialogueApi.projects.commands({ localProjectId: projectRef.current.id, expectedRevision: projectRef.current.revision, source: "ui", commands, summary })); }
      catch (cause) {
        const conflict = cause instanceof DialogueApiError && cause.code === "REVISION_CONFLICT"; const latest = await dialogueApi.projects.get(projectRef.current.id).catch(() => undefined);
        if (latest) { projectRef.current = latest; setProject(latest); onChanged(latest); }
        if (conflict && latest) {
          try { return acceptResult(await dialogueApi.projects.commands({ localProjectId: latest.id, expectedRevision: latest.revision, source: "ui", commands, summary })); }
          catch (retryCause) { setError(readError(retryCause)); throw retryCause; }
        }
        setError(readError(cause)); throw cause;
      }
    }); commandQueue.current = operation; void operation.finally(() => { if (commandQueue.current === operation) setSaving(false); }).catch(() => undefined); return operation;
  }, [acceptResult, onChanged]);

  const seek = useCallback((seconds: number) => { const target = Math.max(0, Math.min(compiled.durationSeconds, seconds)); setCurrentTime(target); player.current?.seek(target); }, [compiled.durationSeconds]);
  const selectLine = useCallback((lineId: string) => { const segment = compiled.segments.find((item) => item.blockId === lineId); setSelectedTarget({ kind: "dialogue", lineId, role: "character", linked: segment?.roles.character.linked ?? true }); if (segment) seek(segment.startSeconds); }, [compiled.segments, seek]);
  const selectTarget = useCallback((target: TimelineEditTarget) => { setSelectedTarget(target); setTab("inspector"); }, []);
  const openAnimation = useCallback((target: TimelineEditTarget) => { setSelectedTarget(target); setAnimationTarget(target); }, []);
  const setAdapter = useCallback((adapter?: ProjectPlayerAdapter) => { player.current = adapter; }, []);
  const updatePlaying = useCallback((next: boolean) => setPlaying(next), []);
  const togglePlayback = useCallback(() => { if (playing) player.current?.pause(); else player.current?.play(); }, [playing]);
  const updateTime = useCallback((seconds: number) => setCurrentTime(seconds), []);

  useEffect(() => { const keyboard = (event: KeyboardEvent) => {
    const target = event.target as HTMLElement | null; if (target?.matches("input,textarea,select,[contenteditable=true]")) return;
    if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") { event.preventDefault(); void (event.shiftKey ? redo() : undo()); }
    else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "y") { event.preventDefault(); void redo(); }
    else if (event.code === "Space") { event.preventDefault(); togglePlayback(); }
  }; window.addEventListener("keydown", keyboard); return () => window.removeEventListener("keydown", keyboard);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [togglePlayback]);

  if (assetsLoading) return <ProjectWorkspaceLoading name={project.name} />;

  async function undo() { if (!projectRef.current.canUndo) return; setSaving(true); try { acceptResult(await dialogueApi.projects.undo(projectRef.current.id, projectRef.current.revision)); } catch (cause) { setError(readError(cause)); } finally { setSaving(false); } }
  async function redo() { if (!projectRef.current.canRedo) return; setSaving(true); try { acceptResult(await dialogueApi.projects.redo(projectRef.current.id, projectRef.current.revision)); } catch (cause) { setError(readError(cause)); } finally { setSaving(false); } }
  async function rename(name: string) { if (!name.trim() || name.trim() === projectRef.current.name) return; try { const updated = await dialogueApi.projects.update({ localProjectId: projectRef.current.id, name: name.trim() }); projectRef.current = updated; setProject(updated); onChanged(updated); } catch (cause) { setError(readError(cause)); } }
  async function generateAndAttachLine(lineId: string) {
    const block = dialogueBlocks(projectRef.current.editorState).find((item) => item.id === lineId); if (!block) return; const character = characters.find((item) => item.id === block.data.characterId);
    const voiceId = projectRef.current.editorState.projectType === "reddit-story" ? block.data.narratorVoiceId : character?.voiceId;
    if (!voiceId) throw new Error(projectRef.current.editorState.projectType === "reddit-story" ? "Choose a narrator voice first." : "Choose a valid character for this line first.");
    if (!block.data.text.trim()) throw new Error("Enter dialogue text first.");
    const clip = await dialogueApi.speech.generate({ voiceId, text: block.data.text, speed: block.data.speechSpeed }); const nextSpeech = [clip, ...speechRef.current.filter((item) => item.id !== clip.id)]; speechRef.current = nextSpeech; setSpeech(nextSpeech);
    await execute([{ kind: "update-dialogue-line", lineId, patch: { speechClipId: clip.id } }, { kind: "set-dialogue-caption-words", lineId, words: null }], `Generated audio for line ${dialogueBlocks(projectRef.current.editorState).findIndex((item) => item.id === lineId) + 1}`);
  }
  async function generateLine(lineId: string) {
    setGenerating(lineId); setError(undefined);
    try { await generateAndAttachLine(lineId); } catch (cause) { setError(readError(cause)); } finally { setGenerating(undefined); }
  }
  async function generateAudioBatch(mode: "missing" | "all", retryLineIds?: string[]) {
    const allLines = dialogueBlocks(projectRef.current.editorState); const availableSpeech = new Set(speechRef.current.map((clip) => clip.id));
    const selected = retryLineIds ? allLines.filter((line) => retryLineIds.includes(line.id)) : mode === "all" ? allLines : allLines.filter((line) => !line.data.speechClipId || !availableSpeech.has(line.data.speechClipId));
    if (!selected.length) return;
    const characterById = new Map(characters.map((character) => [character.id, character]));
    const tasks = selected.map((line): AudioGenerationTask => ({ lineId: line.id, lineNumber: allLines.findIndex((item) => item.id === line.id) + 1, characterName: characterById.get(line.data.characterId)?.name ?? "Missing character", text: line.data.text, status: "queued" }));
    setAudioBatch(tasks); setAudioBatchRunning(true); stopAudioBatch.current = false; setError(undefined);
    for (const task of tasks) {
      if (stopAudioBatch.current) { setAudioBatch((current) => current?.map((item) => item.status === "queued" ? { ...item, status: "stopped" } : item)); break; }
      setGenerating(task.lineId); setAudioBatch((current) => current?.map((item) => item.lineId === task.lineId ? { ...item, status: "generating" } : item));
      try { await generateAndAttachLine(task.lineId); setAudioBatch((current) => current?.map((item) => item.lineId === task.lineId ? { ...item, status: "success", error: undefined } : item)); }
      catch (cause) { setAudioBatch((current) => current?.map((item) => item.lineId === task.lineId ? { ...item, status: "error", error: readError(cause) } : item)); }
    }
    setGenerating(undefined); setAudioBatchRunning(false);
  }
  async function startRender(quality: RenderQuality) { setRenderBusy(true); setRenderError(undefined); try { await commandQueue.current; await dialogueApi.projects.render(projectRef.current.id, quality); await refreshRenders(); } catch (cause) { setRenderError(readError(cause)); } finally { setRenderBusy(false); } }
  async function renderOperation(operation: "cancel" | "retry" | "remove", id: string) { setRenderBusy(true); setRenderError(undefined); try { if (operation === "cancel") await dialogueApi.projects.cancelRender(id); else if (operation === "retry") await dialogueApi.projects.retryRender(id); else await dialogueApi.projects.removeRender(id); await refreshRenders(); } catch (cause) { setRenderError(readError(cause)); } finally { setRenderBusy(false); } }
  async function moveLineFromTimeline(lineId: string, targetStart: number) {
    if (projectRef.current.editorState.timeline.mode === "manual") {
      await execute([{ kind: "set-dialogue-timings", edits: [{ lineId, startSeconds: Number(Math.max(0, targetStart).toFixed(3)) }] }], "Moved a linked dialogue group on the manual timeline"); return;
    }
    const segments = compiled.segments; const currentIndex = segments.findIndex((segment) => segment.blockId === lineId); if (currentIndex < 0) return;
    const moving = segments[currentIndex]; const targetCenter = Math.max(0, targetStart) + moving.durationSeconds / 2;
    const remaining = segments.filter((segment) => segment.blockId !== lineId); const targetIndex = remaining.filter((segment) => segment.startSeconds + segment.durationSeconds / 2 < targetCenter).length;
    if (targetIndex !== currentIndex) {
      const lineIds = remaining.map((segment) => segment.blockId); lineIds.splice(targetIndex, 0, lineId);
      await execute([{ kind: "reorder-dialogue-lines", lineIds }], "Moved a linked dialogue group on the Studio timeline"); return;
    }
    if (currentIndex === 0) return;
    const previous = segments[currentIndex - 1]; const gapAfterSeconds = Math.max(0, Math.min(10, Number((targetStart - previous.endSeconds).toFixed(2))));
    if (Math.abs(gapAfterSeconds - previous.data.gapAfterSeconds) < .01) return;
    await execute([{ kind: "set-dialogue-gap", lineId: previous.blockId, gapAfterSeconds }], "Adjusted dialogue timing on the Studio timeline");
  }
  async function resizeLineFromTimeline(lineId: string, startSeconds: number, durationSeconds: number, sourceStartSeconds?: number) {
    const edit = { lineId, startSeconds: Number(Math.max(0, startSeconds).toFixed(3)), durationSeconds: Number(Math.max(1 / projectRef.current.editorState.canvas.fps, durationSeconds).toFixed(3)),
      ...(sourceStartSeconds === undefined ? {} : { sourceStartSeconds: Number(Math.max(0, sourceStartSeconds).toFixed(3)) }) };
    await execute([{ kind: "set-dialogue-timings", edits: [edit] }], "Trimmed a linked dialogue group on the manual timeline");
  }
  async function editTimelineElements(edits: TimelineElementEdit[]) {
    if (projectRef.current.editorState.timeline.mode === "flow" && edits.length === 1 && edits[0].target.kind === "dialogue" && edits[0].target.linked) return moveLineFromTimeline(edits[0].target.lineId, edits[0].startSeconds);
    const itemEdits = edits.filter((edit): edit is TimelineElementEdit & { target: Extract<TimelineEditTarget, { kind: "item" }> } => edit.target.kind === "item").map((edit) => ({ itemId: edit.target.itemId, patch: {
      startSeconds: Number(Math.max(0, edit.startSeconds).toFixed(3)), ...(edit.durationSeconds === undefined ? {} : { durationSeconds: Number(edit.durationSeconds.toFixed(3)) }),
      ...(edit.sourceStartSeconds === undefined ? {} : { sourceStartSeconds: Number(edit.sourceStartSeconds.toFixed(3)) }), ...(edit.trackId ? { trackId: edit.trackId } : {}),
    } }));
    const linked = edits.filter((edit): edit is TimelineElementEdit & { target: Extract<TimelineEditTarget, { kind: "dialogue" }> } => edit.target.kind === "dialogue" && edit.target.linked);
    const unlinked = edits.filter((edit): edit is TimelineElementEdit & { target: Extract<TimelineEditTarget, { kind: "dialogue" }> } => edit.target.kind === "dialogue" && !edit.target.linked);
    const commands: ProjectCommand[] = []; if (itemEdits.length) commands.push({ kind: "update-timeline-items", edits: itemEdits });
    if (linked.length) commands.push({ kind: "set-dialogue-timings", edits: linked.map((edit) => ({ lineId: edit.target.lineId, startSeconds: Number(Math.max(0, edit.startSeconds).toFixed(3)), ...(edit.durationSeconds === undefined ? {} : { durationSeconds: Number(edit.durationSeconds.toFixed(3)) }), ...(edit.sourceStartSeconds === undefined ? {} : { sourceStartSeconds: Number(edit.sourceStartSeconds.toFixed(3)) }) })) });
    if (unlinked.length) commands.push({ kind: "set-dialogue-role-timings", edits: unlinked.map((edit) => ({ lineId: edit.target.lineId, role: edit.target.role, startSeconds: Number(Math.max(0, edit.startSeconds).toFixed(3)), ...(edit.durationSeconds === undefined ? {} : { durationSeconds: Number(edit.durationSeconds.toFixed(3)) }), ...(edit.sourceStartSeconds === undefined ? {} : { sourceStartSeconds: Number(edit.sourceStartSeconds.toFixed(3)) }), ...(edit.trackId ? { trackId: edit.trackId } : {}) })) });
    if (commands.length) await execute(commands, `Edited ${edits.length} timeline element${edits.length === 1 ? "" : "s"}`);
  }
  async function removeTimelineElements(targets: TimelineEditTarget[]) {
    const itemIds = targets.filter((target): target is Extract<TimelineEditTarget, { kind: "item" }> => target.kind === "item").map((target) => target.itemId);
    const lineIds = [...new Set(targets.filter((target): target is Extract<TimelineEditTarget, { kind: "dialogue" }> => target.kind === "dialogue").map((target) => target.lineId))];
    const commands: ProjectCommand[] = []; if (itemIds.length) commands.push({ kind: "remove-timeline-items", itemIds }); for (const lineId of lineIds) commands.push({ kind: "remove-dialogue-line", lineId });
    if (commands.length) await execute(commands, `Removed ${targets.length} timeline element${targets.length === 1 ? "" : "s"}`);
  }
  async function applyAnimation(motion: ProjectClipMotion, scope: AnimationApplyScope) {
    const target = animationTarget; if (!target) return;
    if (target.kind === "item") {
      const item = projectRef.current.editorState.timeline.items.find((entry) => entry.id === target.itemId); if (!item) return;
      const transition = (item.kind === "image" || item.kind === "video") && motion.entrance.preset !== "none" && item.transition.preset !== "cut" ? { ...item.transition, preset: "cut" as const } : undefined;
      await execute([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { motion, ...(transition ? { transition } : {}) } }] }], `Applied animation to ${item.kind} clip`); return;
    }
    const source = dialogueBlocks(projectRef.current.editorState).find((line) => line.id === target.lineId); if (!source) return;
    const ids = dialogueBlocks(projectRef.current.editorState).filter((line) => scope === "all" || scope === "character" && line.data.characterId === source.data.characterId || scope === "element" && line.id === source.id).map((line) => line.id);
    await execute(ids.map((blockId) => ({ kind: "set-block-motion", blockId, motion } as const)), scope === "all" ? "Applied animation to every dialogue line" : scope === "character" ? "Applied animation to this character" : "Applied animation to dialogue line");
  }

  const characterById = new Map(characters.map((character) => [character.id, character]));
  const isRedditStory = project.editorState.projectType === "reddit-story";
  const hasMissingAssets = Boolean(project.editorState.assets.backgroundId && !selectedBackground) || !isRedditStory && lines.some((line) => { const character = characterById.get(line.data.characterId); return !character || !character.images.some((image) => image.id === line.data.characterImageId); });
  const rendering = renderJobs.some((job) => ["queued","preparing","rendering"].includes(job.status));
  const blockers = hasMissingAssets || compiled.segments.some((segment) => !segment.speech || !segment.data.text.trim() || isRedditStory && !segment.data.narratorVoiceId);
  const animationSubject = animationTarget ? buildAnimationSubject(project.editorState, characters, media, animationTarget) : undefined;
  const previewToolbar = <header className="dialogue-preview-toolbar"><div className="preview-project-identity"><button className="preview-back-button" aria-label="Back to projects" title="Back to projects" onClick={onBack}><ArrowLeft size={16} /></button><div><input className="preview-project-title-input" aria-label="Project name" defaultValue={project.name} key={project.name} onBlur={(event) => void rename(event.target.value)} /><span>{lines.length} line{lines.length === 1 ? "" : "s"} · {readyLines}/{lines.length} voiced · revision {project.revision}</span></div></div><div className="dialogue-head-actions"><div className={`dialogue-save-state ${error ? "failed" : ""}`}>{saving ? <><LoaderCircle className="spin" size={13} /> Saving…</> : error ? "Save failed" : <><Check size={13} /> Saved locally</>}</div><button className="history-button" title="Undo (Ctrl/Cmd+Z)" aria-label="Undo" disabled={!project.canUndo || saving} onClick={() => void undo()}><Undo2 size={15} /></button><button className="history-button" title="Redo (Ctrl/Cmd+Shift+Z)" aria-label="Redo" disabled={!project.canRedo || saving} onClick={() => void redo()}><Redo2 size={15} /></button><button className="render-video-button" title={renderJobs.length ? "Open local render library" : !lines.length ? "Add a dialogue line first" : blockers ? "Generate audio for every line" : "Open local render library"} disabled={saving || (!renderJobs.length && (!lines.length || blockers))} onClick={() => setRenderDialog(true)}>{rendering ? <LoaderCircle className="spin" size={16} /> : <Film size={16} />} {rendering ? "Rendering…" : "Render Video"}{renderJobs.length > 0 && <b>{renderJobs.length}</b>}</button></div></header>;
  return <section className="project-workspace dialogue-workspace">
    <div className="dialogue-editor-frame"><div className="dialogue-editor-shell"><aside className="dialogue-control-panel"><div className="dialogue-tabs">{!isRedditStory && <Tab value="characters" current={tab} onSelect={setTab} icon={<Users size={17} />} label="Characters" />}<Tab value="background" current={tab} onSelect={setTab} icon={<ImageIcon size={17} />} label="Backgrounds" /><Tab value="script" current={tab} onSelect={setTab} icon={<Captions size={17} />} label={isRedditStory ? "Story" : "Script"} /><Tab value="media" current={tab} onSelect={setTab} icon={<Layers3 size={17} />} label="Media" /><Tab value="subtitles" current={tab} onSelect={setTab} icon={<Type size={17} />} label="Subtitles" /><Tab value="inspector" current={tab} onSelect={setTab} icon={<SlidersHorizontal size={17} />} label="Inspector" /></div>{error && <div className="form-error dialogue-error">{error}</div>}
      {tab === "characters" ? <CharacterPanel state={project.editorState} characters={characters} currentTime={currentTime} onToggle={(characterIds) => execute([{ kind: "configure-stage", characterIds }], "Updated project cast")} onAddPose={(characterId, characterImageId) => execute([{ kind: "add-timeline-item", item: { kind: "character-pose", characterId, characterImageId, trackId: "characters", startSeconds: currentTime, durationSeconds: 3 } }], "Added a character pose at the playhead").then((result) => { const added = result.project.editorState.timeline.items.at(-1); if (added) selectTarget({ kind: "item", itemId: added.id }); }).then(() => undefined)} />
      : tab === "background" ? <BackgroundPanel state={project.editorState} backgrounds={backgrounds} selected={selectedBackground} onSelect={(backgroundId) => execute([{ kind: "configure-stage", backgroundId, backgroundStartSeconds: 0 }], "Changed project background")} onOffset={(backgroundStartSeconds) => execute([{ kind: "configure-stage", backgroundStartSeconds }], "Changed background offset")} />
      : tab === "media" ? <MediaPanel state={project.editorState} media={media} currentTime={currentTime} onImported={(asset) => setMedia((items) => [asset, ...items])} onOpenAnimation={(itemId) => openAnimation({ kind: "item", itemId })} onCommand={(commands, summary) => execute(commands, summary).then(() => undefined)} />
      : tab === "subtitles" ? <SubtitleStylePanel style={project.editorState.captions} canvasHeight={project.editorState.canvas.height} onChange={(patch) => execute([{ kind: "set-caption-style", patch }], "Updated subtitle style").then(() => undefined)} />
      : tab === "inspector" ? <InspectorPanel state={project.editorState} timeline={compiled} characters={characters} media={media} selected={selectedTarget} currentTime={currentTime} onOpenAnimation={openAnimation} onCommand={(commands, summary) => execute(commands, summary).then(() => undefined)} />
      : isRedditStory ? <RedditStoryPanel line={lines[0]} voices={voices} speech={speech} generating={Boolean(generating)} onUpdate={(lineId, patch, summary) => execute([{ kind: "update-dialogue-line", lineId, patch }], summary).then(() => undefined)} onGenerate={(lineId) => void generateLine(lineId)} />
      : <ScriptPanel state={project.editorState} characters={characters} speech={speech} selectedLineId={selectedLineId} generating={generating} onSelect={selectLine} onUpdate={(lineId, patch, summary) => execute([{ kind: "update-dialogue-line", lineId, patch }], summary).then(() => undefined)} onSetSpeechSpeed={(speechSpeed) => execute(dialogueBlocks(projectRef.current.editorState).map((line) => ({ kind: "update-dialogue-line" as const, lineId: line.id, patch: { speechSpeed } })), "Changed voice speed for every dialogue clip").then(() => undefined)} onAdd={(speechSpeed) => execute([{ kind: "add-dialogue-line", line: { speechSpeed } }], "Added dialogue line").then((result) => { const added = dialogueBlocks(result.project.editorState).find((line) => !lines.some((old) => old.id === line.id)); if (added) selectLine(added.id); })} onRemove={(lineId) => execute([{ kind: "remove-dialogue-line", lineId }], "Removed dialogue line").then(() => undefined)} onDuplicate={(lineId) => execute([{ kind: "duplicate-dialogue-line", lineId }], "Duplicated dialogue line").then(() => undefined)} onMove={(lineId, direction) => { const ids = dialogueBlocks(projectRef.current.editorState).map((line) => line.id); const index = ids.indexOf(lineId); const target = index + direction; if (target < 0 || target >= ids.length) return Promise.resolve(); [ids[index], ids[target]] = [ids[target], ids[index]]; return execute([{ kind: "reorder-dialogue-lines", lineIds: ids }], "Reordered dialogue lines").then(() => undefined); }} onReorder={(lineIds) => execute([{ kind: "reorder-dialogue-lines", lineIds }], "Reordered dialogue lines by dragging").then(() => undefined)} onCaptionWords={(lineId, words) => execute([{ kind: "set-dialogue-caption-words", lineId, words }], words ? "Corrected word-level captions" : "Reset word-level captions").then(() => undefined)} onOpenAnimation={(lineId) => { const segment = compiled.segments.find((entry) => entry.blockId === lineId); openAnimation({ kind: "dialogue", lineId, role: "character", linked: segment?.roles.character.linked ?? true }); }} onGenerate={(lineId) => void generateLine(lineId)} onGenerateMissing={() => void generateAudioBatch("missing")} onRegenerateAll={() => void generateAudioBatch("all")} onOpenCharacters={() => setTab("characters")} />}
      </aside><div className="dialogue-preview-column">{previewToolbar}<HyperframesPreview project={project} timeline={compiled} media={media} currentTime={currentTime} playing={playing} selectedTarget={selectedTarget} onAdapter={setAdapter} onTime={updateTime} onPlaying={updatePlaying} onSelectLine={selectLine} onSelectTarget={setSelectedTarget} onTransform={(target, transform) => execute(target.kind === "item" ? [{ kind: "update-timeline-items", edits: [{ itemId: target.itemId, patch: { transform } }] }] : [{ kind: "set-block-transform", blockId: target.lineId, transform }], "Positioned an element on canvas").then(() => undefined).catch(() => undefined)} /></div></div>
      <StudioProjectTimeline projectId={project.id} revision={project.revision} fps={project.editorState.canvas.fps} timeline={compiled} tracks={project.editorState.timeline.tracks} media={media} mode={project.editorState.timeline.mode} selectedTarget={selectedTarget} currentTime={currentTime} onSelectTarget={selectTarget} onSeek={seek} onEditElements={editTimelineElements} onRemoveElements={removeTimelineElements} onSetMode={(mode) => execute([{ kind: "set-timeline-mode", mode }], `Switched timeline to ${mode} mode`).then(() => undefined)} />
    </div>{audioBatch && <AudioGenerationProgressDialog tasks={audioBatch} running={audioBatchRunning} onStop={() => { stopAudioBatch.current = true; }} onRetryFailed={() => void generateAudioBatch("all", audioBatch.filter((task) => task.status === "error").map((task) => task.lineId))} onClose={() => setAudioBatch(undefined)} />}{renderDialog && <RenderHistoryDialog jobs={renderJobs} busy={renderBusy} error={renderError} onClose={() => setRenderDialog(false)} onStart={startRender} onCancel={(id) => renderOperation("cancel", id)} onRetry={(id) => renderOperation("retry", id)} onRemove={(id) => renderOperation("remove", id)} />}{animationSubject && <AnimationPickerDialog subject={animationSubject} onClose={() => setAnimationTarget(undefined)} onApply={applyAnimation} />}
  </section>;
}

function ProjectWorkspaceLoading({ name }: { name: string }) {
  return <section className="project-workspace dialogue-workspace workspace-initial-loading" aria-busy="true" aria-label={`Loading ${name}`}>
    <div className="workspace-loading-card"><div className="workspace-loading-icon"><span className="brand-mark" /><LoaderCircle className="spin" size={19} /></div><strong>Preparing your project</strong><span>Loading characters, voices, audio and background…</span><div className="workspace-loading-progress" aria-hidden="true"><i /><i /><i /></div></div>
  </section>;
}

function Tab({ value, current, onSelect, icon, label }: { value: EditorTab; current: EditorTab; onSelect: (value: EditorTab) => void; icon: React.ReactNode; label: string }) { return <button className={current === value ? "active" : ""} onClick={() => onSelect(value)}>{icon}{label}</button>; }

function CharacterPanel({ state, characters, currentTime, onToggle, onAddPose }: { state: ProjectEditorState; characters: CharacterRecord[]; currentTime: number; onToggle: (ids: string[]) => Promise<unknown>; onAddPose: (characterId: string, characterImageId: string) => Promise<void> }) {
  const cast = characters.filter((character) => state.assets.characterIds.includes(character.id)); const knownIds = new Set(characters.map((character) => character.id)); const missingIds = state.assets.characterIds.filter((id) => !knownIds.has(id));
  return <div className="dialogue-panel-scroll"><section className="setup-section"><div><strong>Project cast</strong><span>Used characters stay selected.</span></div><div className="setup-cast">{characters.map((character) => { const selected = state.assets.characterIds.includes(character.id); const used = dialogueBlocks(state).some((line) => line.data.characterId === character.id) || state.timeline.items.some((item) => item.kind === "character-pose" && item.characterId === character.id); return <button key={character.id} className={selected ? "selected" : ""} title={used ? "This character is used by the project" : undefined} onClick={() => { if (selected && used) return; void onToggle(selected ? state.assets.characterIds.filter((id) => id !== character.id) : [...state.assets.characterIds, character.id]); }}>{character.images[0] ? <img src={character.images[0].imageUrl} alt="" /> : <span><Users size={18} /></span>}<div><b>{character.name}</b><small>{character.voiceName} · {character.images.length} pose{character.images.length === 1 ? "" : "s"}</small></div>{selected && <Check size={14} />}</button>; })}</div>{!characters.length && <p className="panel-empty">Create characters in the Character Library first.</p>}</section>
    {cast.length > 0 && <section className="setup-section"><div><strong>Pose clips</strong><span>Add a pose at {currentTime.toFixed(2)}s. Clips may overlap.</span></div><div className="pose-clip-grid">{cast.flatMap((character) => character.images.map((image) => <button key={`${character.id}:${image.id}`} onClick={() => void onAddPose(character.id, image.id)}><img src={image.imageUrl} alt="" /><span><b>{character.name}</b><small>{image.label}</small></span><Plus size={12} /></button>))}</div></section>}
  </div>;
}

function BackgroundPanel({ state, backgrounds, selected, onSelect, onOffset }: { state: ProjectEditorState; backgrounds: BackgroundRecord[]; selected?: BackgroundRecord; onSelect: (id: string) => Promise<unknown>; onOffset: (seconds: number) => Promise<unknown> }) {
  const [offset, setOffset] = useState(state.assets.backgroundStartSeconds); useEffect(() => setOffset(state.assets.backgroundStartSeconds), [state.assets.backgroundStartSeconds]); const missing = Boolean(state.assets.backgroundId && !selected);
  return <div className="dialogue-panel-scroll"><section className="setup-section background-workspace"><div><strong>Background video</strong><span>Choose a video and start time.</span></div>{missing && <div className="asset-recovery-warning"><TriangleAlert size={15} /><span><b>The selected background is missing.</b> Choose a replacement or remove it.</span></div>}{selected && <div className="selected-background-card"><video src={selected.videoUrl} poster={selected.thumbnailUrl} muted loop playsInline preload="metadata" /><div className="selected-background-copy"><span>Selected background</span><strong>{selected.name}</strong><small>{selected.durationSeconds.toFixed(1)} seconds · stored locally</small><label className="background-offset">Start time <b>{offset.toFixed(1)}s / {selected.durationSeconds.toFixed(1)}s</b><input type="range" min={0} max={Math.max(0, selected.durationSeconds - .1)} step={.1} value={Math.min(offset, selected.durationSeconds)} onChange={(event) => setOffset(Number(event.target.value))} onPointerUp={() => void onOffset(offset)} onKeyUp={() => void onOffset(offset)} /></label></div></div>}<div className="background-library-heading"><div><strong>Background library</strong><span>{backgrounds.length} local video{backgrounds.length === 1 ? "" : "s"}</span></div>{state.assets.backgroundId && <button className="secondary-button" onClick={() => void onSelect("")}>Remove background</button>}</div><div className="setup-backgrounds">{backgrounds.map((background) => <button key={background.id} className={selected?.id === background.id ? "selected" : ""} onClick={() => void onSelect(background.id)}><video src={background.videoUrl} poster={background.thumbnailUrl} muted preload="metadata" /><b>{background.name}</b><small>{background.durationSeconds.toFixed(1)}s</small></button>)}</div>{!backgrounds.length && <p className="panel-empty">Add videos in the Background Library first.</p>}</section></div>;
}

function InspectorPanel({ state, timeline, characters, media, selected, currentTime, onOpenAnimation, onCommand }: { state: ProjectEditorState; timeline: ReturnType<typeof compileDialogueTimeline>; characters: CharacterRecord[]; media: ProjectMediaAssetRecord[]; selected?: TimelineEditTarget; currentTime: number; onOpenAnimation: (target: TimelineEditTarget) => void; onCommand: (commands: ProjectCommand[], summary: string) => Promise<void> }) {
  if (!selected) return <div className="script-empty inspector-empty"><span><SlidersHorizontal size={25} /></span><h3>Select an element</h3><p>Choose a clip on the timeline or canvas to edit its properties.</p></div>;
  const target = selected; const item = target.kind === "item" ? state.timeline.items.find((entry) => entry.id === target.itemId) : undefined;
  const segment = target.kind === "dialogue" ? timeline.segments.find((entry) => entry.blockId === target.lineId) : undefined; const block = target.kind === "dialogue" ? state.blocks.find((entry) => entry.id === target.lineId) : undefined;
  const roleWindow = target.kind === "dialogue" ? segment?.roles[target.role] : undefined; const clipWindow = item ?? roleWindow;
  if (!clipWindow) return <div className="script-empty inspector-empty"><h3>Element unavailable</h3><p>The selected clip may have been removed.</p></div>;
  const track = state.timeline.tracks.find((entry) => entry.id === clipWindow.trackId); const asset = item?.assetId ? media.find((entry) => entry.id === item.assetId) : undefined;
  const character = item?.kind === "character-pose" ? characters.find((entry) => entry.id === item.characterId) : target.kind === "dialogue" ? characters.find((entry) => entry.id === segment?.data.characterId) : undefined;
  const characterImage = item?.kind === "character-pose" ? character?.images.find((image) => image.id === item.characterImageId) : target.kind === "dialogue" ? character?.images.find((image) => image.id === segment?.data.characterImageId) : undefined;
  const kind = item?.kind ?? (target.kind === "dialogue" ? target.role : "element"); const label = item ? item.kind === "character-pose" ? `${character?.name ?? "Character"} - ${characterImage?.label ?? "Pose"}` : item.text || asset?.name || titleCase(kind) : target.kind === "dialogue" && target.role === "character" ? character?.name ?? "Dialogue character" : `Dialogue ${titleCase(kind)}`;
  const isVisual = item ? item.kind !== "audio" : target.kind === "dialogue" && target.role === "character"; const canAnimate = target.kind === "dialogue" && target.role === "character" || Boolean(item && ["image","video","character-pose"].includes(item.kind));
  const transform = item?.transform ?? block?.timeline?.transform ?? (segment ? defaultDialogueCharacterTransform(segment.data.position) : undefined); const motion = normalizeProjectMotion(item?.motion ?? block?.timeline?.motion);
  function timing(patch: Partial<{ startSeconds: number; durationSeconds: number; sourceStartSeconds: number; trackId: string }>) {
    if (item) return onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch }] }], `Updated ${label} timing`);
    if (!segment || target.kind !== "dialogue" || !roleWindow) return Promise.resolve(); const next = { ...roleWindow, ...patch };
    if (target.linked) { const commands: ProjectCommand[] = state.timeline.mode === "manual" ? [] : [{ kind: "set-timeline-mode", mode: "manual" }]; commands.push({ kind: "set-dialogue-timings", edits: [{ lineId: target.lineId, startSeconds: next.startSeconds, durationSeconds: next.durationSeconds, sourceStartSeconds: next.sourceStartSeconds }] }); return onCommand(commands, "Updated linked dialogue timing"); }
    return onCommand([{ kind: "set-dialogue-role-timings", edits: [{ lineId: target.lineId, role: target.role, startSeconds: next.startSeconds, durationSeconds: next.durationSeconds, sourceStartSeconds: next.sourceStartSeconds, trackId: next.trackId }] }], `Updated dialogue ${target.role} timing`);
  }
  function setTransform(patch: Partial<ProjectElementTransform>) { if (!isVisual) return Promise.resolve(); return item ? onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { transform: patch } }] }], `Transformed ${label}`) : target.kind === "dialogue" ? onCommand([{ kind: "set-block-transform", blockId: target.lineId, transform: patch }], "Transformed dialogue character") : Promise.resolve(); }
  function applyDialogueTransform() { if (target.kind !== "dialogue" || !segment || !transform) return; const patch = { xPercent: transform.xPercent, yPercent: transform.yPercent, widthPercent: transform.widthPercent, heightPercent: transform.heightPercent }; const ids = dialogueBlocks(state).filter((line) => line.data.characterId === segment.data.characterId).map((line) => line.id); void onCommand(ids.map((blockId) => ({ kind: "set-block-transform", blockId, transform: patch } as const)), "Applied character layout to matching dialogue lines"); }
  const mediaSource = asset?.mediaUrl ?? characterImage?.imageUrl;
  return <div className="dialogue-panel-scroll inspector-panel inspector-panel-v2">
    <section className={`inspector-heading kind-${kind}`}><span>{kind === "image" || kind === "character-pose" ? <ImageIcon size={18} /> : kind === "video" ? <Film size={18} /> : kind === "audio" || kind === "speech" ? <Mic2 size={18} /> : kind === "text" || kind === "captions" ? <Type size={18} /> : kind === "character" ? <Users size={18} /> : <SlidersHorizontal size={18} />}</span><div><small>Selected {kind.replace("-", " ")}</small><strong>{label}</strong><em>{track?.name ?? clipWindow.trackId} track</em></div></section>
    <InspectorPreview kind={kind} label={label} source={mediaSource} text={item?.text} start={clipWindow.startSeconds} duration={clipWindow.durationSeconds} />
    {item?.kind === "character-pose" && <InspectorSectionV2 title="Pose" description="Choose the artwork displayed by this clip."><div className="inspector-grid"><label className="inspector-field"><span>Character</span><select value={item.characterId} onChange={(event) => { const next = characters.find((entry) => entry.id === event.target.value); if (next?.images[0]) void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { characterId: next.id, characterImageId: next.images[0].id } }] }], "Changed pose character"); }}>{characters.filter((entry) => state.assets.characterIds.includes(entry.id)).map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label className="inspector-field"><span>Pose</span><select value={item.characterImageId} onChange={(event) => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { characterImageId: event.target.value } }] }], "Changed character pose")}>{character?.images.map((image) => <option key={image.id} value={image.id}>{image.label}</option>)}</select></label></div></InspectorSectionV2>}
    <InspectorSectionV2 title="Timing" description="Place and trim this clip on the project timeline."><div className="inspector-grid timing"><InspectorNumber label="Start" value={clipWindow.startSeconds} suffix="s" min={0} step={1 / state.canvas.fps} onCommit={(value) => timing({ startSeconds: value })} /><InspectorNumber label="Duration" value={clipWindow.durationSeconds} suffix="s" min={1 / state.canvas.fps} step={1 / state.canvas.fps} onCommit={(value) => timing({ durationSeconds: value })} /><InspectorNumber label="Media offset" value={clipWindow.sourceStartSeconds} suffix="s" min={0} step={1 / state.canvas.fps} disabled={item?.kind === "image" || item?.kind === "text" || item?.kind === "character-pose" || target.kind === "dialogue" && target.role === "character"} onCommit={(value) => timing({ sourceStartSeconds: value })} /><label className="inspector-field"><span>Track</span><select value={clipWindow.trackId} onChange={(event) => void timing({ trackId: event.target.value })}>{state.timeline.tracks.filter((entry) => item?.kind === "audio" || target.kind === "dialogue" && target.role === "speech" ? entry.kind === "audio" : entry.kind !== "audio").map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label></div></InspectorSectionV2>
    {isVisual && transform && <InspectorSectionV2 title="Position & size" description={`Position on the ${state.canvas.width} x ${state.canvas.height} canvas.`}><div className="inspector-position-presets"><button onClick={() => void setTransform({ xPercent: 25 })}>Left</button><button onClick={() => void setTransform({ xPercent: 50 })}>Center</button><button onClick={() => void setTransform({ xPercent: 75 })}>Right</button><button onClick={() => void setTransform({ ...DEFAULT_PROJECT_TRANSFORM, widthPercent: 100, heightPercent: 100 })}>Fill</button></div><div className="inspector-slider-stack"><InspectorSlider label="Horizontal" value={transform.xPercent} suffix="%" min={-50} max={150} onCommit={(value) => setTransform({ xPercent: value })} /><InspectorSlider label="Vertical" value={transform.yPercent} suffix="%" min={-50} max={150} onCommit={(value) => setTransform({ yPercent: value })} /><InspectorSlider label="Width" value={transform.widthPercent} suffix="%" min={1} max={200} onCommit={(value) => setTransform({ widthPercent: value })} /><InspectorSlider label="Height" value={transform.heightPercent} suffix="%" min={1} max={200} onCommit={(value) => setTransform({ heightPercent: value })} /><InspectorSlider label="Rotation" value={transform.rotationDegrees} suffix="deg" min={-180} max={180} onCommit={(value) => setTransform({ rotationDegrees: value })} /><InspectorSlider label="Opacity" value={transform.opacity} min={0} max={1} step={.05} onCommit={(value) => setTransform({ opacity: value })} /></div><div className="inspector-layer-row"><InspectorNumber label="Layer order" value={transform.zIndex} min={-1000} max={1000} step={1} onCommit={(value) => setTransform({ zIndex: Math.round(value) })} />{target.kind === "dialogue" && <button onClick={applyDialogueTransform}>Apply layout to all {character?.name ?? "character"} lines</button>}</div></InspectorSectionV2>}
    {item && (item.kind === "audio" || item.kind === "video") && <InspectorSectionV2 title="Playback" description="Control how the source media plays."><div className="inspector-slider-stack"><InspectorSlider label="Volume" value={item.volume} min={0} max={1} step={.05} onCommit={(volume) => onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { volume } }] }], "Updated media volume")} /><InspectorSlider label="Speed" value={item.playbackRate} suffix="x" min={.25} max={4} step={.05} onCommit={(playbackRate) => onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { playbackRate } }] }], "Updated playback speed")} /></div><div className="inspector-inline-actions"><button className={item.muted ? "active" : ""} onClick={() => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { muted: !item.muted } }] }], item.muted ? "Unmuted media" : "Muted media")}>{item.muted ? "Muted" : "Mute"}</button><button className={item.loop ? "active" : ""} onClick={() => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { loop: !item.loop } }] }], item.loop ? "Disabled media loop" : "Looped media")}>{item.loop ? "Looping" : "Loop"}</button><button disabled={currentTime <= item.startSeconds || currentTime >= item.startSeconds + item.durationSeconds} onClick={() => void onCommand([{ kind: "split-timeline-item", itemId: item.id, atSeconds: currentTime }], "Split media at playhead")}>Split at {currentTime.toFixed(2)}s</button></div></InspectorSectionV2>}
    {canAnimate && <InspectorSectionV2 title="Animation" description="Animate the entrance, on-screen motion, or exit."><button className="inspector-animation-launch" onClick={() => onOpenAnimation(target)}><span><Sparkles size={17} /></span><div><strong>Choose animation</strong><small>Preview every style before applying it</small></div></button><div className="inspector-animation-summary">{(["entrance","during","exit","combo"] as const).map((phase) => <span key={phase}><small>{phase === "during" ? "On screen" : phase === "combo" ? "Full clip" : phase}</small><b>{motionPresetName(motion[phase].preset)}</b></span>)}</div></InspectorSectionV2>}
    {item && (item.kind === "image" || item.kind === "video") && <InspectorSectionV2 title="Scene transition" description="Blend this clip into the scene."><div className="inspector-motion-row"><label><span>Transition in</span><select value={item.transition.preset} onChange={(event) => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { transition: { ...item.transition, preset: event.target.value as typeof item.transition.preset } } }] }], "Updated scene transition")}><option value="cut">Cut</option><option value="fade">Fade</option><option value="crossfade">Crossfade</option><option value="slide">Slide</option><option value="zoom">Zoom</option></select></label><InspectorNumber label="Duration" value={item.transition.durationSeconds} suffix="s" min={0} max={10} step={.05} onCommit={(value) => onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { transition: { ...item.transition, durationSeconds: value } } }] }], "Updated scene transition duration")} /></div></InspectorSectionV2>}
    {target.kind === "dialogue" && target.role === "captions" && <InspectorSectionV2 title="Caption motion" description="Choose how caption pages appear."><div className="inspector-motion-row"><label><span>Preset</span><select value={state.captionAnimation.preset} onChange={(event) => void onCommand([{ kind: "set-caption-animation", patch: { preset: event.target.value as ProjectEditorState["captionAnimation"]["preset"] } }], "Updated caption animation")}><option value="none">None</option><option value="pop">Pop</option><option value="word-reveal">Word reveal</option><option value="karaoke">Karaoke pulse</option><option value="bounce">Bounce</option></select></label><InspectorNumber label="Duration" value={state.captionAnimation.durationSeconds} suffix="s" min={0} max={3} step={.05} onCommit={(value) => onCommand([{ kind: "set-caption-animation", patch: { durationSeconds: value } }], "Updated caption animation duration")} /></div></InspectorSectionV2>}
  </div>;
}

function InspectorPreview({ kind, label, source, text, start, duration }: { kind: string; label: string; source?: string; text?: string; start: number; duration: number }) { return <section className="inspector-preview"><div className={`inspector-preview-media ${kind}`}>{source && kind === "video" ? <video src={source} muted preload="metadata" /> : source ? <img src={source} alt="" /> : kind === "audio" || kind === "speech" ? <span className="inspector-audio-wave"><Mic2 size={20} /><i /><i /><i /><i /><i /></span> : <span className="inspector-text-preview">{text || label}</span>}</div><div className="inspector-preview-meta"><span><small>Starts</small><b>{start.toFixed(2)}s</b></span><span><small>Duration</small><b>{duration.toFixed(2)}s</b></span><span><small>Ends</small><b>{(start + duration).toFixed(2)}s</b></span></div></section>; }
function InspectorSectionV2({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="inspector-section inspector-section-v2"><div className="inspector-section-heading"><h4>{title}</h4>{description && <p>{description}</p>}</div>{children}</section>; }
function InspectorSlider({ label, value, suffix, min, max, step = .1, onCommit }: { label: string; value: number; suffix?: string; min: number; max: number; step?: number; onCommit: (value: number) => void | Promise<void> }) { const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]); const commit = () => { if (Number.isFinite(draft) && Math.abs(draft - value) > 1e-6) void onCommit(draft); }; return <label className="inspector-slider"><span>{label}<b>{Number(draft.toFixed(2))}{suffix}</b></span><div><input type="range" min={min} max={max} step={step} value={draft} onChange={(event) => setDraft(Number(event.target.value))} onPointerUp={commit} onKeyUp={commit} /><input type="number" min={min} max={max} step={step} value={Number(draft.toFixed(2))} onChange={(event) => setDraft(Math.max(min, Math.min(max, Number(event.target.value))))} onBlur={commit} /></div></label>; }
function titleCase(value: string) { return value.split("-").map((part) => part ? part[0].toUpperCase() + part.slice(1) : part).join(" "); }

function LegacyInspectorPanel({ state, timeline, characters, media, selected, currentTime, onOpenAnimation, onCommand }: { state: ProjectEditorState; timeline: ReturnType<typeof compileDialogueTimeline>; characters: CharacterRecord[]; media: ProjectMediaAssetRecord[]; selected?: TimelineEditTarget; currentTime: number; onOpenAnimation: (target: TimelineEditTarget) => void; onCommand: (commands: ProjectCommand[], summary: string) => Promise<void> }) {
  if (!selected) return <div className="script-empty inspector-empty"><span><SlidersHorizontal size={25} /></span><h3>Select an element</h3><p>Select a timeline clip to edit timing, transform and motion.</p></div>;
  const target = selected;
  const item = selected.kind === "item" ? state.timeline.items.find((entry) => entry.id === selected.itemId) : undefined;
  const segment = selected.kind === "dialogue" ? timeline.segments.find((entry) => entry.blockId === selected.lineId) : undefined;
  const block = selected.kind === "dialogue" ? state.blocks.find((entry) => entry.id === selected.lineId) : undefined;
  const roleWindow = selected.kind === "dialogue" ? segment?.roles[selected.role] : undefined; const window = item ?? roleWindow;
  if (!window) return <div className="script-empty inspector-empty"><h3>Element unavailable</h3><p>The selected clip may have been removed.</p></div>;
  const track = state.timeline.tracks.find((entry) => entry.id === window.trackId); const character = item?.kind === "character-pose" ? characters.find((entry) => entry.id === item.characterId) : selected.kind === "dialogue" ? characters.find((entry) => entry.id === segment?.data.characterId) : undefined;
  const label = item ? item.kind === "character-pose" ? `${character?.name ?? "Character"} · ${character?.images.find((image) => image.id === item.characterImageId)?.label ?? "Pose"}` : item.text || media.find((asset) => asset.id === item.assetId)?.name || item.kind : `Dialogue ${selected.kind === "dialogue" ? selected.role : "element"}`;
  const isVisual = item ? item.kind !== "audio" : selected.kind === "dialogue" && selected.role === "character"; const canAnimate = selected.kind === "dialogue" && selected.role === "character" || Boolean(item && ["image","video","character-pose"].includes(item.kind)); const transform = item?.transform ?? block?.timeline?.transform ?? (segment ? defaultDialogueCharacterTransform(segment.data.position) : undefined);
  const motion = normalizeProjectMotion(item?.motion ?? block?.timeline?.motion);
  function timing(patch: Partial<{ startSeconds: number; durationSeconds: number; sourceStartSeconds: number; trackId: string }>) {
    if (item) return onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch }] }], `Updated ${label} timing`);
    if (!segment || target.kind !== "dialogue" || !roleWindow) return Promise.resolve(); const next = { ...roleWindow, ...patch };
    if (target.linked) { const commands: ProjectCommand[] = state.timeline.mode === "manual" ? [] : [{ kind: "set-timeline-mode", mode: "manual" }]; commands.push({ kind: "set-dialogue-timings", edits: [{ lineId: target.lineId, startSeconds: next.startSeconds, durationSeconds: next.durationSeconds, sourceStartSeconds: next.sourceStartSeconds }] }); return onCommand(commands, "Updated linked dialogue timing"); }
    return onCommand([{ kind: "set-dialogue-role-timings", edits: [{ lineId: target.lineId, role: target.role, startSeconds: next.startSeconds, durationSeconds: next.durationSeconds, sourceStartSeconds: next.sourceStartSeconds, trackId: next.trackId }] }], `Updated dialogue ${target.role} timing`);
  }
  function setTransform(patch: Partial<ProjectElementTransform>) { if (!isVisual) return Promise.resolve(); return item ? onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { transform: patch } }] }], `Transformed ${label}`) : target.kind === "dialogue" ? onCommand([{ kind: "set-block-transform", blockId: target.lineId, transform: patch }], "Transformed dialogue character") : Promise.resolve(); }
  function applyDialogueTransform() { if (target.kind !== "dialogue" || !segment || !transform) return; const transformPatch = { xPercent: transform.xPercent, yPercent: transform.yPercent, widthPercent: transform.widthPercent, heightPercent: transform.heightPercent }; const ids = dialogueBlocks(state).filter((line) => line.data.characterId === segment.data.characterId).map((line) => line.id); void onCommand(ids.map((blockId) => ({ kind: "set-block-transform", blockId, transform: transformPatch } as const)), "Applied character position and size to every matching dialogue line"); }
  return <div className="dialogue-panel-scroll inspector-panel"><section className="inspector-heading"><span><SlidersHorizontal size={15} /></span><div><strong>{label}</strong><small>{item ? item.kind : target.kind === "dialogue" ? target.role : "element"} · {track?.name ?? window.trackId}</small></div></section>
    {item?.kind === "character-pose" && <InspectorSection title="Pose"><div className="inspector-grid"><label className="inspector-field"><span>Character</span><select value={item.characterId} onChange={(event) => { const next = characters.find((entry) => entry.id === event.target.value); if (next?.images[0]) void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { characterId: next.id, characterImageId: next.images[0].id } }] }], "Changed pose character"); }}>{characters.filter((entry) => state.assets.characterIds.includes(entry.id)).map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label className="inspector-field"><span>Image</span><select value={item.characterImageId} onChange={(event) => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { characterImageId: event.target.value } }] }], "Changed character pose")}>{character?.images.map((image) => <option key={image.id} value={image.id}>{image.label}</option>)}</select></label></div></InspectorSection>}
    <InspectorSection title="Timing"><div className="inspector-grid timing"><InspectorNumber label="Start" value={window.startSeconds} suffix="s" min={0} step={1 / state.canvas.fps} onCommit={(value) => timing({ startSeconds: value })} /><InspectorNumber label="Duration" value={window.durationSeconds} suffix="s" min={1 / state.canvas.fps} step={1 / state.canvas.fps} onCommit={(value) => timing({ durationSeconds: value })} /><InspectorNumber label="Source" value={window.sourceStartSeconds} suffix="s" min={0} step={1 / state.canvas.fps} disabled={item?.kind === "image" || item?.kind === "text" || item?.kind === "character-pose" || selected.kind === "dialogue" && selected.role === "character"} onCommit={(value) => timing({ sourceStartSeconds: value })} /><label className="inspector-field"><span>Track</span><select value={window.trackId} onChange={(event) => void timing({ trackId: event.target.value })}>{state.timeline.tracks.filter((entry) => item?.kind === "audio" || selected.kind === "dialogue" && selected.role === "speech" ? entry.kind === "audio" : entry.kind !== "audio").map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label></div></InspectorSection>
    {isVisual && transform && <InspectorSection title="Canvas"><div className="inspector-grid transform"><InspectorNumber label="X" value={transform.xPercent} suffix="%" min={-100} max={200} onCommit={(value) => setTransform({ xPercent: value })} /><InspectorNumber label="Y" value={transform.yPercent} suffix="%" min={-100} max={200} onCommit={(value) => setTransform({ yPercent: value })} /><InspectorNumber label="Width" value={transform.widthPercent} suffix="%" min={1} max={300} onCommit={(value) => setTransform({ widthPercent: value })} /><InspectorNumber label="Height" value={transform.heightPercent} suffix="%" min={1} max={300} onCommit={(value) => setTransform({ heightPercent: value })} /><InspectorNumber label="Rotate" value={transform.rotationDegrees} suffix="°" min={-360} max={360} onCommit={(value) => setTransform({ rotationDegrees: value })} /><InspectorNumber label="Opacity" value={transform.opacity} min={0} max={1} step={.05} onCommit={(value) => setTransform({ opacity: value })} /><InspectorNumber label="Layer" value={transform.zIndex} min={-1000} max={1000} step={1} onCommit={(value) => setTransform({ zIndex: Math.round(value) })} /></div></InspectorSection>}
    {target.kind === "dialogue" && isVisual && <InspectorSection title="Character layout"><div className="inspector-inline-actions"><button onClick={applyDialogueTransform}>Apply position &amp; size to this character</button></div></InspectorSection>}
    {item && (item.kind === "audio" || item.kind === "video") && <InspectorSection title="Playback"><div className="inspector-grid timing"><InspectorNumber label="Volume" value={item.volume} min={0} max={1} step={.05} onCommit={(volume) => onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { volume } }] }], "Updated media volume")} /><InspectorNumber label="Speed" value={item.playbackRate} suffix="x" min={.25} max={4} step={.05} onCommit={(playbackRate) => onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { playbackRate } }] }], "Updated playback speed")} /></div><div className="inspector-inline-actions"><button className={item.muted ? "active" : ""} onClick={() => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { muted: !item.muted } }] }], item.muted ? "Unmuted media" : "Muted media")}>{item.muted ? "Muted" : "Mute"}</button><button className={item.loop ? "active" : ""} onClick={() => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { loop: !item.loop } }] }], item.loop ? "Disabled media loop" : "Looped media")}>{item.loop ? "Looping" : "Loop"}</button><button disabled={currentTime <= item.startSeconds || currentTime >= item.startSeconds + item.durationSeconds} onClick={() => void onCommand([{ kind: "split-timeline-item", itemId: item.id, atSeconds: currentTime }], "Split media at playhead")}>Split at {currentTime.toFixed(2)}s</button></div></InspectorSection>}
    {canAnimate && <InspectorSection title="Animation"><button className="inspector-animation-launch" onClick={() => onOpenAnimation(target)}><span><Sparkles size={17} /></span><div><strong>Choose animation</strong><small>Preview every style before applying it</small></div></button><div className="inspector-animation-summary">{(["entrance","during","exit","combo"] as const).map((phase) => <span key={phase}><small>{phase === "during" ? "On screen" : phase === "combo" ? "Full clip" : phase}</small><b>{motionPresetName(motion[phase].preset)}</b></span>)}</div></InspectorSection>}
    {item && (item.kind === "image" || item.kind === "video") && <InspectorSection title="Scene transition"><div className="inspector-motion-row"><label><span>Transition in</span><select value={item.transition.preset} onChange={(event) => void onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { transition: { ...item.transition, preset: event.target.value as typeof item.transition.preset } } }] }], "Updated scene transition")}><option value="cut">Cut</option><option value="fade">Fade</option><option value="crossfade">Crossfade</option><option value="slide">Slide</option><option value="zoom">Zoom</option></select></label><InspectorNumber label="Duration" value={item.transition.durationSeconds} suffix="s" min={0} max={10} step={.05} onCommit={(value) => onCommand([{ kind: "update-timeline-items", edits: [{ itemId: item.id, patch: { transition: { ...item.transition, durationSeconds: value } } }] }], "Updated scene transition duration")} /></div></InspectorSection>}
    {selected.kind === "dialogue" && selected.role === "captions" && <InspectorSection title="Caption motion"><div className="inspector-motion-row"><label><span>Preset</span><select value={state.captionAnimation.preset} onChange={(event) => void onCommand([{ kind: "set-caption-animation", patch: { preset: event.target.value as ProjectEditorState["captionAnimation"]["preset"] } }], "Updated caption animation")}><option value="none">None</option><option value="pop">Pop</option><option value="word-reveal">Word reveal</option><option value="karaoke">Karaoke pulse</option><option value="bounce">Bounce</option></select></label><InspectorNumber label="Duration" value={state.captionAnimation.durationSeconds} suffix="s" min={0} max={3} step={.05} onCommit={(value) => onCommand([{ kind: "set-caption-animation", patch: { durationSeconds: value } }], "Updated caption animation duration")} /></div></InspectorSection>}
  </div>;
}

function InspectorSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="inspector-section"><h4>{title}</h4>{children}</section>; }
function InspectorNumber({ label, value, suffix, min, max, step = .1, disabled, onCommit }: { label: string; value: number; suffix?: string; min?: number; max?: number; step?: number; disabled?: boolean; onCommit: (value: number) => void | Promise<void> }) { return <label className="inspector-field"><span>{label}</span><i><input key={value} type="number" defaultValue={Number(value.toFixed(3))} min={min} max={max} step={step} disabled={disabled} onBlur={(event) => { const next = Number(event.target.value); if (Number.isFinite(next) && Math.abs(next - value) > 1e-6) void onCommit(Math.max(min ?? -Infinity, Math.min(max ?? Infinity, next))); }} />{suffix && <em>{suffix}</em>}</i></label>; }
function MediaPanel({ state, media, currentTime, onImported, onOpenAnimation, onCommand }: { state: ProjectEditorState; media: ProjectMediaAssetRecord[]; currentTime: number; onImported: (asset: ProjectMediaAssetRecord) => void; onOpenAnimation: (itemId: string) => void; onCommand: (commands: ProjectCommand[], summary: string) => Promise<void> }) {
  const [uploading, setUploading] = useState(false); const [text, setText] = useState("");
  const addAsset = (asset: ProjectMediaAssetRecord) => onCommand([{ kind: "add-timeline-item", item: { kind: asset.kind, assetId: asset.id, trackId: asset.kind === "audio" ? "audio" : "overlays", startSeconds: currentTime } }], `Added ${asset.name} to timeline`);
  async function upload(file?: File) { if (!file) return; setUploading(true); try { const metadata = await inspectLocalMedia(file); const asset = await dialogueApi.media.create({ name: file.name.replace(/\.[^.]+$/, ""), file: { name: file.name, mimeType: metadata.mimeType, bytes: new Uint8Array(await file.arrayBuffer()) }, width: metadata.width, height: metadata.height, durationSeconds: metadata.durationSeconds }); onImported(asset); } finally { setUploading(false); } }
  return <div className="dialogue-panel-scroll media-panel"><section className="setup-section"><div><strong>Local media</strong><span>Images, videos, audio, and text overlays are reusable across projects.</span></div>
    <div className="media-panel-actions"><label className="secondary-button media-upload"><Upload size={13} /> {uploading ? "Importing…" : "Import media"}<input type="file" disabled={uploading} accept="image/png,image/jpeg,image/webp,video/mp4,video/webm,video/quicktime,audio/wav,audio/mpeg,audio/ogg,audio/mp4" onChange={(event) => { void upload(event.target.files?.[0]); event.target.value = ""; }} /></label></div>
    <div className="media-text-add"><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Add a text overlay" /><button disabled={!text.trim()} onClick={() => { void onCommand([{ kind: "add-timeline-item", item: { kind: "text", text: text.trim(), trackId: "overlays", startSeconds: currentTime, durationSeconds: 3 } }], "Added text overlay"); setText(""); }}><Type size={13} /> Add</button></div>
    <div className="media-library-grid">{media.map((asset) => { const count = state.timeline.items.filter((item) => item.assetId === asset.id).length; return <div className="media-asset-card" key={asset.id}>{asset.kind === "image" ? <img src={asset.mediaUrl} alt="" /> : asset.kind === "video" ? <video src={asset.mediaUrl} muted preload="metadata" /> : <span><Mic2 size={18} /></span>}<b>{asset.name}</b><small>{asset.kind}{asset.durationSeconds ? ` · ${asset.durationSeconds.toFixed(1)}s` : ""}{count ? ` · ${count} on timeline` : ""}</small><button onClick={() => void addAsset(asset)}><Plus size={11} /> Add at playhead</button></div>; })}</div>{!media.length && <p className="panel-empty">Import a local media file to start.</p>}
  </section><section className="setup-section"><div><strong>Timeline instances</strong><span>Each use of a library asset appears here and on the timeline.</span></div><div className="timeline-item-list">{state.timeline.items.map((item) => <div key={item.id}><span><b>{item.kind === "text" ? item.text : media.find((asset) => asset.id === item.assetId)?.name ?? item.kind}</b><small>{item.kind} · {item.startSeconds.toFixed(2)}s · {item.durationSeconds.toFixed(2)}s</small></span>{["image","video","character-pose"].includes(item.kind) && <button className="timeline-animation-button" title="Choose animation" aria-label={`Choose animation for ${item.kind} clip`} onClick={() => onOpenAnimation(item.id)}><Sparkles size={12} /></button>}<button title="Remove timeline instance" aria-label={`Remove ${item.kind} timeline instance`} onClick={() => void onCommand([{ kind: "remove-timeline-items", itemIds: [item.id] }], "Removed media from timeline")}><Trash2 size={12} /></button></div>)}</div>{!state.timeline.items.length && <p className="panel-empty">Add a library asset at the playhead to create a timeline instance.</p>}</section></div>;
}

function RedditStoryPanel({ line, voices, speech, generating, onUpdate, onGenerate }: {
  line?: ReturnType<typeof dialogueBlocks>[number]; voices: VoiceRecord[]; speech: SpeechClipRecord[]; generating: boolean;
  onUpdate: (lineId: string, patch: Partial<DialogueLineData>, summary: string) => Promise<void>; onGenerate: (lineId: string) => void;
}) {
  const post = line?.data.redditPost ?? { sourceUrl: "", subreddit: "stories", username: "storyteller", postedAgo: "3h", title: "Untitled Reddit story", upvotes: "0", comments: "0" };
  const [title, setTitle] = useState(post.title); const [story, setStory] = useState(line?.data.text ?? "");
  const [subreddit, setSubreddit] = useState(post.subreddit); const [username, setUsername] = useState(post.username); const [postedAgo, setPostedAgo] = useState(post.postedAgo); const [upvotes, setUpvotes] = useState(post.upvotes); const [comments, setComments] = useState(post.comments);
  useEffect(() => { if (!line) return; const next = line.data.redditPost; setStory(line.data.text); if (next) { setTitle(next.title); setSubreddit(next.subreddit); setUsername(next.username); setPostedAgo(next.postedAgo); setUpvotes(next.upvotes); setComments(next.comments); } }, [line]);
  if (!line) return <div className="script-empty"><span><TriangleAlert size={25} /></span><h3>Story setup is missing</h3><p>Create a new Reddit Story project to restore the starter card.</p></div>;
  const linkedSpeech = line.data.speechClipId ? speech.find((clip) => clip.id === line.data.speechClipId) : undefined;
  const currentPost = (): RedditPostData => ({ sourceUrl: line.data.redditPost?.sourceUrl ?? "", subreddit, username, postedAgo, title, upvotes, comments });
  const savePost = (summary: string) => onUpdate(line.id, { redditPost: currentPost() }, summary);
  return <div className="dialogue-panel-scroll reddit-story-panel"><section className="setup-section reddit-post-fields"><div><strong>Reddit card</strong><span>This animated card opens the video over your selected background.</span></div><label>Post title<textarea rows={3} maxLength={300} value={title} onChange={(event) => setTitle(event.target.value)} onBlur={() => void savePost("Updated Reddit post title")} /></label><div className="reddit-meta-grid"><label>Subreddit<input maxLength={80} value={subreddit} onChange={(event) => setSubreddit(event.target.value)} onBlur={() => void savePost("Updated subreddit")} /></label><label>Username<input maxLength={80} value={username} onChange={(event) => setUsername(event.target.value)} onBlur={() => void savePost("Updated Reddit username")} /></label><label>Posted<input maxLength={20} value={postedAgo} onChange={(event) => setPostedAgo(event.target.value)} onBlur={() => void savePost("Updated post age")} /></label><label>Upvotes<input maxLength={20} value={upvotes} onChange={(event) => setUpvotes(event.target.value)} onBlur={() => void savePost("Updated upvotes")} /></label><label>Comments<input maxLength={20} value={comments} onChange={(event) => setComments(event.target.value)} onBlur={() => void savePost("Updated comment count")} /></label></div></section>
    <section className="setup-section"><div><strong>Story narration</strong><span>The full story becomes voiceover and word-timed captions.</span></div><textarea className="reddit-story-text" rows={12} maxLength={20000} value={story} onChange={(event) => setStory(event.target.value)} onBlur={() => { if (story !== line.data.text) void onUpdate(line.id, { text: story }, "Updated Reddit story"); }} /><small className="reddit-character-count">{story.length.toLocaleString()} / 20,000 characters</small><div className="reddit-voice-row"><label>Narrator<select value={line.data.narratorVoiceId ?? ""} onChange={(event) => void onUpdate(line.id, { narratorVoiceId: event.target.value || undefined }, "Changed Reddit narrator")}><option value="">Choose a voice</option>{voices.map((voice) => <option key={voice.id} value={voice.id}>{voice.name} · {voice.provider}</option>)}</select></label><label>Speed<select value={line.data.speechSpeed} onChange={(event) => void onUpdate(line.id, { speechSpeed: event.target.value as DialogueLineData["speechSpeed"] }, "Changed narration speed")}><option value="slow">Slow</option><option value="normal">Normal</option><option value="fast">Fast</option></select></label></div><label className="line-checkbox"><input type="checkbox" checked={line.data.hideSubtitles} onChange={(event) => void onUpdate(line.id, { hideSubtitles: event.target.checked }, event.target.checked ? "Hid story subtitles" : "Showed story subtitles")} /> Hide subtitles</label><div className="reddit-generate-row"><span className={linkedSpeech ? "audio-ready" : "audio-missing"}>{linkedSpeech ? <><Check size={11} /> Narration synced · {linkedSpeech.durationSeconds.toFixed(1)}s</> : "Narration needs audio"}</span><button className="primary-button" disabled={generating || !story.trim() || !line.data.narratorVoiceId} onClick={() => onGenerate(line.id)}>{generating ? <LoaderCircle className="spin" size={13} /> : <Mic2 size={13} />} {generating ? "Generating…" : linkedSpeech ? "Regenerate narration" : "Generate narration"}</button></div>{linkedSpeech && <audio className="reddit-audio-preview" controls preload="metadata" src={linkedSpeech.audioUrl} />}</section>
  </div>;
}

function ScriptPanel({ state, characters, speech, selectedLineId, generating, onSelect, onUpdate, onSetSpeechSpeed, onAdd, onRemove, onDuplicate, onMove, onReorder, onCaptionWords, onOpenAnimation, onGenerate, onGenerateMissing, onRegenerateAll, onOpenCharacters }: {
  state: ProjectEditorState; characters: CharacterRecord[]; speech: SpeechClipRecord[]; selectedLineId?: string; generating?: string; onSelect: (id: string) => void;
  onUpdate: (lineId: string, patch: Partial<DialogueLineData>, summary?: string) => Promise<void>; onSetSpeechSpeed: (speed: DialogueLineData["speechSpeed"]) => Promise<void>; onAdd: (speed: DialogueLineData["speechSpeed"]) => Promise<unknown>; onRemove: (id: string) => Promise<void>; onDuplicate: (id: string) => Promise<void>; onMove: (id: string, direction: -1 | 1) => Promise<void>; onReorder: (ids: string[]) => Promise<void>; onCaptionWords: (id: string, words: import("@/shared/contracts").SpeechWord[] | null) => Promise<void>; onOpenAnimation: (id: string) => void; onGenerate: (id: string) => void; onGenerateMissing: () => void; onRegenerateAll: () => void; onOpenCharacters: () => void;
}) {
  const cast = characters.filter((character) => state.assets.characterIds.includes(character.id)); const lines = dialogueBlocks(state); const speechById = new Map(speech.map((clip) => [clip.id, clip]));
  const voicedCount = lines.filter((line) => line.data.speechClipId && speechById.has(line.data.speechClipId)).length; const missingCount = lines.length - voicedCount;
  const sharedSpeechSpeed: DialogueLineData["speechSpeed"] | "" = lines.length && lines.every((line) => line.data.speechSpeed === lines[0].data.speechSpeed) ? lines[0].data.speechSpeed : "";
  const [draggedId, setDraggedId] = useState<string>(); const [editingCaptions, setEditingCaptions] = useState<string>(); const [playingId, setPlayingId] = useState<string>(); const audition = useRef<HTMLAudioElement | undefined>(undefined);
  useEffect(() => () => { audition.current?.pause(); }, []);
  function toggleAudition(blockId: string, clip: SpeechClipRecord) { if (playingId === blockId && audition.current && !audition.current.paused) { audition.current.pause(); setPlayingId(undefined); return; } audition.current?.pause(); const audio = new Audio(clip.audioUrl); audition.current = audio; audio.onended = () => setPlayingId(undefined); audio.onerror = () => setPlayingId(undefined); void audio.play().then(() => setPlayingId(blockId)); }
  function dropOn(targetId: string) { if (!draggedId || draggedId === targetId) return setDraggedId(undefined); const ids = lines.map((line) => line.id); const from = ids.indexOf(draggedId); const to = ids.indexOf(targetId); ids.splice(to, 0, ids.splice(from, 1)[0]); setDraggedId(undefined); void onReorder(ids); }
  if (!cast.length && !lines.length) return <div className="script-empty"><span><Users size={25} /></span><h3>Select your cast</h3><p>Choose one or more characters before writing dialogue.</p><button className="primary-button" onClick={onOpenCharacters}>Open characters</button></div>;
  const captionLine = editingCaptions ? lines.find((line) => line.id === editingCaptions) : undefined; const captionClip = captionLine?.data.speechClipId ? speechById.get(captionLine.data.speechClipId) : undefined;
  return <><div className="dialogue-panel-scroll"><div className="script-toolbar"><div className="script-toolbar-summary"><strong>Dialogue clips</strong><span>{voicedCount}/{lines.length} voiced</span></div><div className="script-voice-configuration"><label><span>Voice configuration</span><select aria-label="Voice speed for all dialogue clips" value={sharedSpeechSpeed} disabled={!lines.length || Boolean(generating)} onChange={(event) => void onSetSpeechSpeed(event.target.value as DialogueLineData["speechSpeed"])}>{!sharedSpeechSpeed && <option value="" disabled>Mixed speeds</option>}<option value="slow">Slow</option><option value="normal">Normal</option><option value="fast">Fast</option></select></label><small>Speed applies to every clip. Changing it requires new audio.</small></div><div className="script-audio-actions"><button className="secondary-button" disabled={!missingCount || Boolean(generating)} title={!missingCount ? "Every dialogue clip already has audio" : `Generate audio for ${missingCount} missing ${missingCount === 1 ? "clip" : "clips"}`} onClick={onGenerateMissing}><Mic2 size={14} /> Generate missing{missingCount ? ` (${missingCount})` : ""}</button><button className="secondary-button" disabled={!lines.length || Boolean(generating)} onClick={onRegenerateAll}><Mic2 size={14} /> Regenerate all</button></div></div>{!cast.length && <div className="asset-recovery-warning"><TriangleAlert size={15} /><span><b>The project cast is unavailable.</b> Open Characters to add replacements, then repair the affected lines.</span><button onClick={onOpenCharacters}>Open characters</button></div>}<div className="dialogue-lines">{lines.map((block, index) => { const clip = block.data.speechClipId ? speechById.get(block.data.speechClipId) : undefined; return <DialogueLineCard key={block.id} block={block} index={index} total={lines.length} cast={cast} speechClip={clip} playing={playingId === block.id} selected={block.id === selectedLineId} generating={generating === block.id} dragging={draggedId === block.id} onDragStart={() => setDraggedId(block.id)} onDrop={() => dropOn(block.id)} onSelect={onSelect} onUpdate={onUpdate} onRemove={onRemove} onDuplicate={onDuplicate} onMove={onMove} onGenerate={onGenerate} onAudition={() => clip && toggleAudition(block.id, clip)} onEditCaptions={() => setEditingCaptions(block.id)} onOpenAnimation={() => onOpenAnimation(block.id)} />; })}</div><button className="add-dialogue-line" disabled={!cast.length} title={!cast.length ? "Add a project character first" : undefined} onClick={() => void onAdd(sharedSpeechSpeed || "fast")}><Plus size={15} /> Add dialogue clip</button></div>
    {captionLine && captionClip && <CaptionWordEditor words={captionLine.data.captionWordsOverride ?? captionClip.words} durationSeconds={captionClip.durationSeconds} customized={Boolean(captionLine.data.captionWordsOverride)} onSave={(words) => onCaptionWords(captionLine.id, words)} onReset={() => onCaptionWords(captionLine.id, null)} onClose={() => setEditingCaptions(undefined)} />}</>;
}

function DialogueLineCard({ block, index, total, cast, speechClip, playing, selected, generating, dragging, onDragStart, onDrop, onSelect, onUpdate, onRemove, onDuplicate, onMove, onGenerate, onAudition, onEditCaptions, onOpenAnimation }: {
  block: ReturnType<typeof dialogueBlocks>[number]; index: number; total: number; cast: CharacterRecord[]; speechClip?: SpeechClipRecord; playing: boolean; selected: boolean; generating: boolean; dragging: boolean; onDragStart: () => void; onDrop: () => void;
  onSelect: (id: string) => void; onUpdate: (id: string, patch: Partial<DialogueLineData>, summary?: string) => Promise<void>; onRemove: (id: string) => Promise<void>; onDuplicate: (id: string) => Promise<void>; onMove: (id: string, direction: -1 | 1) => Promise<void>; onGenerate: (id: string) => void; onAudition: () => void; onEditCaptions: () => void; onOpenAnimation: () => void;
}) {
  const [text, setText] = useState(block.data.text); const character = cast.find((item) => item.id === block.data.characterId); const poses = character?.images ?? []; const missingCharacter = !character; const missingPose = Boolean(character && !poses.some((image) => image.id === block.data.characterImageId)); const invalidReason = missingCharacter ? "Assigned character is missing. Choose a replacement." : missingPose ? "Assigned pose is missing. Choose a replacement." : undefined; const hasSpeech = Boolean(speechClip);
  useEffect(() => setText(block.data.text), [block.data.text]);
  useEffect(() => { if (text === block.data.text) return; const timer = window.setTimeout(() => void onUpdate(block.id, { text }, `Edited dialogue line ${index + 1}`), 750); return () => window.clearTimeout(timer); }, [block.data.text, block.id, index, onUpdate, text]);
  return <article className={`${hasSpeech ? "voiced" : ""} ${selected ? "selected" : ""} ${dragging ? "dragging" : ""} ${invalidReason ? "invalid-asset" : ""}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); onDrop(); }} onClick={() => onSelect(block.id)}><button className="line-drag-handle" draggable onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", block.id); onDragStart(); }} aria-label={`Drag dialogue line ${index + 1}`} title="Drag to reorder"><GripVertical size={14} /></button><div className="line-number">{index + 1}</div>{character?.images[0] && <img className="line-character-avatar" src={character.images.find((image) => image.id === block.data.characterImageId)?.imageUrl ?? character.images[0].imageUrl} alt="" />}{invalidReason && <div className="line-asset-warning"><TriangleAlert size={13} /> {invalidReason}</div>}<div className="line-character-row"><select aria-label="Character" value={character?.id ?? ""} onClick={(event) => event.stopPropagation()} onChange={(event) => { const next = cast.find((item) => item.id === event.target.value); if (next?.images[0]) void onUpdate(block.id, { characterId: next.id, characterImageId: next.images[0].id }, `Changed character on line ${index + 1}`); }}>{missingCharacter && <option value="">Missing character</option>}{cast.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Character pose" value={missingPose ? "" : block.data.characterImageId} disabled={!character} onClick={(event) => event.stopPropagation()} onChange={(event) => void onUpdate(block.id, { characterImageId: event.target.value }, `Changed pose on line ${index + 1}`)}>{missingPose && <option value="">Missing pose</option>}{poses.map((image) => <option key={image.id} value={image.id}>{image.label}</option>)}</select><select className="position-select" aria-label="Character position" value={block.data.position} onClick={(event) => event.stopPropagation()} onChange={(event) => void onUpdate(block.id, { position: event.target.value as DialogueLineData["position"] }, `Changed position on line ${index + 1}`)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></div>
    <textarea rows={3} value={text} onClick={(event) => event.stopPropagation()} onChange={(event) => setText(event.target.value)} onBlur={() => { if (text !== block.data.text) void onUpdate(block.id, { text }, `Edited dialogue line ${index + 1}`); }} />
    {speechClip && character && poses.length > 1 && <PerformanceCueEditor block={block} character={character} speechClip={speechClip} onUpdate={onUpdate} />}
    <div className="line-actions"><span className={hasSpeech ? "audio-ready" : "audio-missing"}>{hasSpeech ? <><Check size={11} /> Audio synced</> : "Needs audio"}</span>{hasSpeech && <><button title={playing ? "Pause audio" : "Preview audio"} aria-label={playing ? "Pause audio" : "Preview audio"} onClick={(event) => { event.stopPropagation(); onAudition(); }}>{playing ? <Pause size={12} /> : <Play size={12} />}</button><button title="Correct word-level captions" aria-label="Correct word-level captions" onClick={(event) => { event.stopPropagation(); onEditCaptions(); }}><Captions size={12} /></button></>}<button className="line-animation-button" title="Choose character animation" aria-label="Choose character animation" onClick={(event) => { event.stopPropagation(); onOpenAnimation(); }}><Sparkles size={12} /></button><button title="Move line up" aria-label="Move line up" disabled={!index} onClick={(event) => { event.stopPropagation(); void onMove(block.id, -1); }}><ArrowUp size={13} /></button><button title="Move line down" aria-label="Move line down" disabled={index === total - 1} onClick={(event) => { event.stopPropagation(); void onMove(block.id, 1); }}><ArrowDown size={13} /></button><button title="Duplicate line" aria-label="Duplicate line" onClick={(event) => { event.stopPropagation(); void onDuplicate(block.id); }}><Copy size={12} /></button><button className="generate-line" disabled={generating || !text.trim() || Boolean(invalidReason)} title={invalidReason} onClick={(event) => { event.stopPropagation(); onGenerate(block.id); }}>{generating ? <LoaderCircle className="spin" size={12} /> : <Mic2 size={12} />} {hasSpeech ? "Regenerate" : "Generate"}</button><button className="danger" title="Remove line" aria-label="Remove line" onClick={(event) => { event.stopPropagation(); if (window.confirm(`Remove dialogue line ${index + 1}?`)) void onRemove(block.id); }}><Trash2 size={13} /></button></div>
  </article>;
}

function PerformanceCueEditor({ block, character, speechClip, onUpdate }: { block: ReturnType<typeof dialogueBlocks>[number]; character: CharacterRecord; speechClip: SpeechClipRecord; onUpdate: (id: string, patch: Partial<DialogueLineData>, summary?: string) => Promise<void> }) {
  const words = (block.data.captionWordsOverride ?? speechClip.words).filter((word) => word.type === "word"); const poses = character.images;
  const [wordIndex, setWordIndex] = useState(0); const [poseId, setPoseId] = useState(poses.find((pose) => pose.id !== block.data.characterImageId)?.id ?? poses[0]?.id ?? ""); const cues = block.data.performanceCues ?? [];
  function addCue() { const word = words[wordIndex]; if (!word || !poseId) return; const same = words.filter((candidate, index) => index <= wordIndex && candidate.text.normalize("NFKC").toLocaleLowerCase() === word.text.normalize("NFKC").toLocaleLowerCase()).length;
    const cue: import("@/shared/contracts").DialoguePerformanceCue = { id: crypto.randomUUID(), characterImageId: poseId, at: { wordIndex, exact: word.text, occurrence: same,
      prefix: words.slice(Math.max(0, wordIndex - 3), wordIndex).map((entry) => entry.text).join(" "), suffix: words.slice(wordIndex + 1, wordIndex + 4).map((entry) => entry.text).join(" ") } };
    void onUpdate(block.id, { performanceCues: [...cues, cue] }, `Added a pose change to dialogue clip`); }
  return <div className="performance-cue-editor" onClick={(event) => event.stopPropagation()}><div><strong>Performance</strong><span>Change pose on a spoken word.</span></div>{cues.length > 0 && <div className="performance-cue-list">{cues.map((cue) => <span key={cue.id}>“{cue.at.exact}” → {poses.find((pose) => pose.id === cue.characterImageId)?.label ?? "Missing pose"}<button aria-label={`Remove pose change on ${cue.at.exact}`} onClick={() => void onUpdate(block.id, { performanceCues: cues.filter((entry) => entry.id !== cue.id) }, "Removed a dialogue pose change")}>×</button></span>)}</div>}
    <div className="performance-cue-add"><select aria-label="Pose change word" value={Math.min(wordIndex, Math.max(0, words.length - 1))} onChange={(event) => setWordIndex(Number(event.target.value))}>{words.map((word, index) => <option value={index} key={`${index}:${word.startSeconds}`}>{word.text} · {word.startSeconds.toFixed(2)}s</option>)}</select><select aria-label="Pose after word" value={poseId} onChange={(event) => setPoseId(event.target.value)}>{poses.map((pose) => <option value={pose.id} key={pose.id}>{pose.label}</option>)}</select><button disabled={!words.length || !poseId} onClick={addCue}><Plus size={11} /> Add cue</button></div></div>;
}

function buildAnimationSubject(state: ProjectEditorState, characters: CharacterRecord[], media: ProjectMediaAssetRecord[], target: TimelineEditTarget): AnimationPickerSubject | undefined {
  if (target.kind === "dialogue") {
    if (target.role !== "character") return undefined; const line = dialogueBlocks(state).find((entry) => entry.id === target.lineId); if (!line) return undefined;
    const character = characters.find((entry) => entry.id === line.data.characterId); const image = character?.images.find((entry) => entry.id === line.data.characterImageId) ?? character?.images[0];
    return { label: character?.name ?? "Dialogue character", detail: image?.label ?? "Character image", assetKind: "image", assetUrl: image?.imageUrl, previewFit: "character", motion: line.timeline?.motion, characterScopes: true };
  }
  const item = state.timeline.items.find((entry) => entry.id === target.itemId); if (!item || !["image","video","character-pose"].includes(item.kind)) return undefined;
  if (item.kind === "character-pose") {
    const character = characters.find((entry) => entry.id === item.characterId); const image = character?.images.find((entry) => entry.id === item.characterImageId);
    return { label: character?.name ?? "Character pose", detail: image?.label ?? "Pose clip", assetKind: "image", assetUrl: image?.imageUrl, previewFit: "character", motion: item.motion };
  }
  const asset = media.find((entry) => entry.id === item.assetId); return { label: asset?.name ?? `${item.kind} clip`, detail: item.kind === "video" ? "Video clip" : "Image clip", assetKind: item.kind === "video" ? "video" : "image", assetUrl: asset?.mediaUrl, motion: item.motion };
}

function readError(cause: unknown) { return cause instanceof Error ? cause.message : String(cause); }

async function inspectLocalMedia(file: File): Promise<{ mimeType: string; width: number; height: number; durationSeconds: number }> {
  const extension = file.name.split(".").at(-1)?.toLowerCase(); const mimeType = file.type || ({ png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp", mp4: "video/mp4", webm: "video/webm", mov: "video/quicktime", wav: "audio/wav", mp3: "audio/mpeg", ogg: "audio/ogg", m4a: "audio/mp4" } as Record<string, string>)[extension ?? ""];
  if (!mimeType) throw new Error("Unsupported media type."); const url = URL.createObjectURL(file);
  try {
    if (mimeType.startsWith("image/")) return await new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve({ mimeType, width: image.naturalWidth, height: image.naturalHeight, durationSeconds: 0 }); image.onerror = () => reject(new Error("The image could not be inspected.")); image.src = url; });
    const media = document.createElement(mimeType.startsWith("video/") ? "video" : "audio"); media.preload = "metadata"; media.src = url;
    return await new Promise((resolve, reject) => { media.onloadedmetadata = () => resolve({ mimeType, width: media instanceof HTMLVideoElement ? media.videoWidth : 0, height: media instanceof HTMLVideoElement ? media.videoHeight : 0, durationSeconds: media.duration }); media.onerror = () => reject(new Error("The media file could not be inspected.")); });
  } finally { URL.revokeObjectURL(url); }
}
