import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const directory = await mkdtemp(join(tmpdir(), "dialoguelab-parity-")); process.env.DIALOGUELAB_DATA_DIR = directory; let closeDatabase: (() => void) | undefined;
try {
  const { db } = await import("../src/server/database"); const database = db(); closeDatabase = () => database.close(); const now = new Date().toISOString();
  const voiceId = crypto.randomUUID(); const characterId = crypto.randomUUID(); const imageId = crypto.randomUUID(); const speechId = crypto.randomUUID();
  database.prepare("INSERT INTO voices(id,provider,provider_voice_id,name,description,kind,created_at) VALUES (?,'elevenlabs','fixture','Fixture voice','','existing',?)").run(voiceId, now);
  database.prepare("INSERT INTO characters(id,name,description,voice_id,created_at) VALUES (?,'Fixture character','',?,?)").run(characterId, voiceId, now);
  database.prepare("INSERT INTO character_images(id,character_id,label,mime_type,image_data,width,height,sort_order,created_at) VALUES (?,?,'Default','image/png',?,320,640,0,?)").run(imageId, characterId, Buffer.from([0]), now);
  const { speechRepository } = await import("../src/server/speech-repository"); speechRepository.create({ id: speechId, voiceId, voiceName: "Fixture voice", provider: "elevenlabs", providerVoiceId: "fixture", text: "original words", model: "fixture", speed: "normal", storageName: "fixture.wav", mimeType: "audio/wav", sizeBytes: 1, durationSeconds: 2, timingSource: "provider", createdAt: now, words: [{ text: "original", type: "word", startSeconds: 0, endSeconds: 1 }, { text: "words", type: "word", startSeconds: 1, endSeconds: 2 }] });
  const { mediaService, projectService } = await import("../src/server/services"); const { projectCommandService } = await import("../src/server/project-command-service");
  const audio = await mediaService.create({ name: "Loop", file: { name: "loop.wav", mimeType: "audio/wav", bytes: new Uint8Array([1]) }, width: 0, height: 0, durationSeconds: 2 });
  const project = projectService.create({ name: "Parity", description: "", width: 1080, height: 1920, fps: 30 });
  const built = projectCommandService.apply({ localProjectId: project.id, source: "system", commands: [{ kind: "configure-stage", characterIds: [characterId] }, { kind: "add-dialogue-line", line: { characterId, characterImageId: imageId, text: "original words", speechClipId: speechId, position: "center", speechSpeed: "normal", gapAfterSeconds: .2, hideSubtitles: false } }, { kind: "add-timeline-item", item: { kind: "audio", assetId: audio.id, trackId: "audio", startSeconds: 0, durationSeconds: 4, volume: .4, playbackRate: .75, muted: false, loop: true } }] });
  const lineId = built.timeline.segments[0].blockId; const itemId = built.project.editorState.timeline.items[0].id;
  const corrected = [{ text: "corrected", type: "word" as const, startSeconds: 0, endSeconds: .9 }, { text: "caption", type: "word" as const, startSeconds: .9, endSeconds: 2 }];
  const edited = projectCommandService.apply({ localProjectId: project.id, expectedRevision: built.revision, source: "ui", commands: [{ kind: "set-dialogue-caption-words", lineId, words: corrected }, { kind: "set-caption-style", patch: { verticalPositionPx: 1450, switchCaptionsEveryMs: 700 } }, { kind: "set-block-motion", blockId: lineId, motion: { during: { preset: "float", durationSeconds: .4, easing: "gentle", direction: "up" } } }, { kind: "split-timeline-item", itemId, atSeconds: 2 }] });
  assert.deepEqual(edited.timeline.segments[0].data.captionWordsOverride, corrected); assert.equal(edited.project.editorState.timeline.items.length, 2); assert.equal(edited.project.editorState.timeline.items[1].sourceStartSeconds, 1.5); assert.equal(edited.project.editorState.timeline.items[1].loop, true); assert.equal(edited.project.editorState.timeline.items[0].volume, .4);
  const { compileProjectToHyperframes } = await import("../src/server/hyperframes-composition"); const composition = compileProjectToHyperframes({ project: edited.project, characters: [{ id: characterId, name: "Fixture character", description: "", voiceId, voiceName: "Fixture voice", voiceProvider: "elevenlabs", createdAt: now, images: [{ id: imageId, label: "Default", width: 320, height: 640, imageUrl: "" }] }], speechClips: speechRepository.list(), assets: { gsapUrl: "./gsap.js", characterImageUrls: new Map([[imageId, "./character.png"]]), speechUrls: new Map([[speechId, "./speech.wav"]]), mediaUrls: new Map([[audio.id, "./loop.wav"]]) } });
  assert.match(composition.html, /corrected/); assert.match(composition.html, /top:1450px/); assert.match(composition.html, /data-playback-rate="0.75"/); assert.match(composition.html, /data-volume="0.4"/); assert.match(composition.html, / loop/); assert.match(composition.html, /repeat/);
  assert.match(composition.html, /\.dialogue-caption\{[^}]*display:block;white-space:nowrap[^}]*text-align:center/); assert.match(composition.html, /function fitDialogueCaptions\(\)/); assert.doesNotMatch(composition.html, /\.dialogue-caption\{[^}]*flex-wrap:wrap/);
  console.log(JSON.stringify({ ok: true, wordCaptionCorrection: true, preciseCaptionControls: true, centeredSingleLineCaptions: true, responsiveCaptionFit: true, duringMotion: true, mediaPlayback: true, mediaSplit: true, hyperframesParity: true }, null, 2));
} finally { closeDatabase?.(); await rm(directory, { recursive: true, force: true }); }
