import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const directory = await mkdtemp(join(tmpdir(), "dialoguelab-motion-")); process.env.DIALOGUELAB_DATA_DIR = directory; let closeDatabase: (() => void) | undefined;
try {
  const { db } = await import("../src/server/database"); const database = db(); closeDatabase = () => database.close(); const now = new Date().toISOString();
  const voiceId = crypto.randomUUID(); const characterId = crypto.randomUUID(); const poseA = crypto.randomUUID(); const poseB = crypto.randomUUID(); const speechId = crypto.randomUUID();
  database.prepare("INSERT INTO voices(id,provider,provider_voice_id,name,description,kind,created_at) VALUES (?,'elevenlabs','motion','Motion voice','','existing',?)").run(voiceId, now);
  database.prepare("INSERT INTO characters(id,name,description,voice_id,created_at) VALUES (?,'Motion character','',?,?)").run(characterId, voiceId, now);
  const insertImage = database.prepare("INSERT INTO character_images(id,character_id,label,mime_type,image_data,width,height,sort_order,created_at) VALUES (?,?,?,'image/png',?,320,640,?,?)");
  insertImage.run(poseA, characterId, "Neutral", Buffer.from([0]), 0, now); insertImage.run(poseB, characterId, "Surprised", Buffer.from([0]), 1, now);
  const { speechRepository } = await import("../src/server/speech-repository"); speechRepository.create({ id: speechId, voiceId, voiceName: "Motion voice", provider: "elevenlabs", providerVoiceId: "motion", text: "Motion stays synchronized", model: "fixture", speed: "normal", storageName: "motion.wav", mimeType: "audio/wav", sizeBytes: 1, durationSeconds: 2, timingSource: "provider", createdAt: now, words: [{ text: "Motion", type: "word", startSeconds: 0, endSeconds: .7 }, { text: "stays", type: "word", startSeconds: .7, endSeconds: 1.2 }, { text: "synchronized", type: "word", startSeconds: 1.2, endSeconds: 2 }] });
  const { mediaService, projectService } = await import("../src/server/services"); const { projectCommandService } = await import("../src/server/project-command-service"); const { CAPTION_PRESETS } = await import("../src/shared/project-timeline");
  const overlay = await mediaService.create({ name: "Scene card", file: { name: "scene.png", mimeType: "image/png", bytes: new Uint8Array([1]) }, width: 640, height: 360, durationSeconds: 0 });
  const created = projectService.create({ name: "Motion fixture", description: "", width: 1080, height: 1920, fps: 30 });
  const built = projectCommandService.apply({ localProjectId: created.id, expectedRevision: 0, source: "system", commands: [{ kind: "configure-stage", characterIds: [characterId] }, { kind: "add-dialogue-line", line: { characterId, characterImageId: poseA, text: "Motion stays synchronized", speechClipId: speechId, position: "left", speechSpeed: "normal", gapAfterSeconds: 0, hideSubtitles: false } }, { kind: "add-timeline-item", item: { kind: "character-pose", characterId, characterImageId: poseB, trackId: "characters", startSeconds: .5, durationSeconds: 1.2 } }, { kind: "add-timeline-item", item: { kind: "image", assetId: overlay.id, trackId: "overlays", startSeconds: .25, durationSeconds: 1.5 } }] });
  const lineId = built.timeline.segments[0].blockId; const poseItem = built.project.editorState.timeline.items.find((item) => item.kind === "character-pose")!; const imageItem = built.project.editorState.timeline.items.find((item) => item.kind === "image")!;
  const edited = projectCommandService.apply({ localProjectId: created.id, expectedRevision: built.revision, source: "ui", commands: [
    { kind: "set-block-motion", blockId: lineId, motion: { entrance: { preset: "slide", durationSeconds: .3, easing: "smooth", direction: "left" }, exit: { preset: "fade", durationSeconds: .2, easing: "gentle", direction: "down" } } },
    { kind: "set-caption-style", patch: CAPTION_PRESETS["hf-block-pop"] },
    { kind: "set-caption-animation", patch: { preset: "karaoke", durationSeconds: .18 } },
    { kind: "update-timeline-items", edits: [{ itemId: poseItem.id, patch: { transform: { xPercent: 72, yPercent: 68 }, motion: { entrance: { preset: "pop", durationSeconds: .25, easing: "smooth", direction: "up" } } } }, { itemId: imageItem.id, patch: { transition: { preset: "crossfade", durationSeconds: .35, direction: "left" } } }] },
  ] });
  assert.equal(edited.project.editorState.schemaVersion, 14); assert.equal(edited.project.editorState.captions.presetId, "hf-block-pop"); assert.equal(edited.project.editorState.captionAnimation.preset, "karaoke"); assert.equal(edited.timeline.tracks.find((track) => track.id === "characters")?.clips.filter((clip) => clip.kind === "character-pose").length, 1);
  const { compileProjectToHyperframes } = await import("../src/server/hyperframes-composition"); const composition = compileProjectToHyperframes({ project: edited.project, characters: [{ id: characterId, name: "Motion character", description: "", voiceId, voiceName: "Motion voice", voiceProvider: "elevenlabs", createdAt: now, images: [{ id: poseA, label: "Neutral", width: 320, height: 640, imageUrl: "" }, { id: poseB, label: "Surprised", width: 320, height: 640, imageUrl: "" }] }], speechClips: speechRepository.list(), assets: { gsapUrl: "./gsap.js", characterImageUrls: new Map([[poseA, "./neutral.png"], [poseB, "./surprised.png"]]), speechUrls: new Map([[speechId, "./speech.wav"]]), mediaUrls: new Map([[overlay.id, "./scene.png"]]) } });
  assert.equal(composition.renderable, true); assert.match(composition.html, new RegExp(`data-hf-id="item:${poseItem.id}"`)); assert.match(composition.html, /caption-motion-/); assert.match(composition.html, /caption-surface/); assert.match(composition.html, /caption-word active/); assert.match(composition.html, /8px 8px 0px rgba\(0,0,0,1\)/); assert.match(composition.html, /motion-character-/); assert.match(composition.html, /motion-item-/); assert.match(composition.html, /power2\.inOut/); assert.doesNotMatch(composition.html, /fromTo\([^\n]*\.clip/);
  console.log(JSON.stringify({ ok: true, schemaVersion: 14, inspectorContracts: true, characterPoseClips: true, simultaneousCharacters: true, seekSafeMotion: true, captionMotion: true, sceneTransitions: true }, null, 2));
} finally { closeDatabase?.(); await rm(directory, { recursive: true, force: true }); }
