import assert from "node:assert/strict";
import { copyFile, mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";

const keepArtifacts = process.argv.includes("--keep"); const backgroundFlag = process.argv.indexOf("--background"); const backgroundPath = backgroundFlag >= 0 ? process.argv[backgroundFlag + 1] : undefined; const directory = await mkdtemp(join(tmpdir(), "dialoguelab-fake-text-")); const require = createRequire(import.meta.url); process.env.DIALOGUELAB_DATA_DIR = join(directory, "data"); let closeDatabase: (() => void) | undefined;
try {
  const database = await import("../src/server/database"); const projectDb = database.db(); closeDatabase = () => projectDb.close();
  const { projectService } = await import("../src/server/services"); const { projectCommandService } = await import("../src/server/project-command-service"); const { fakeTextBlocks, fakeTextDurationSeconds } = await import("../src/shared/project-timeline"); const { compileProjectToHyperframes } = await import("../src/server/hyperframes-composition");
  const created = projectService.create({ name: "Fake Text verification", description: "", projectType: "fake-text", width: 1080, height: 1920, fps: 30 });
  assert.equal(created.editorState.projectType, "fake-text"); assert.equal(fakeTextBlocks(created.editorState).length, 4); assert.ok(fakeTextDurationSeconds(created.editorState) > 5);
  const first = fakeTextBlocks(created.editorState)[0]; const edited = projectCommandService.apply({ localProjectId: created.id, expectedRevision: created.revision, source: "ui", commands: [{ kind: "update-fake-text-message", messageId: first.id, patch: { text: "A deterministic incoming message", sender: "Verifier" } }, { kind: "set-fake-text-settings", patch: { staggerSeconds: .7, outgoingBubbleColor: "#007AFF" } }], summary: "Edited Fake Text fixture" });
  const added = projectCommandService.apply({ localProjectId: created.id, expectedRevision: edited.revision, source: "mcp", commands: [{ kind: "add-fake-text-message", message: { side: "outgoing", sender: "You", text: "And a fifth message" } }], summary: "Added Fake Text fixture message" });
  assert.equal(fakeTextBlocks(added.project.editorState).length, 5); assert.equal(added.project.editorState.fakeText?.outgoingBubbleColor, "#007AFF"); assert.equal(added.timeline.tracks[0]?.clips.length, 5);
  const assets = join(directory, "assets"); await mkdir(assets); await copyFile(require.resolve("gsap/dist/gsap.min.js"), join(assets, "gsap.min.js")); if (backgroundPath) await copyFile(backgroundPath, join(assets, "gameplay.mp4"));
  const composition = compileProjectToHyperframes({ project: added.project, characters: [], speechClips: [], assets: { gsapUrl: "./assets/gsap.min.js", backgroundUrl: backgroundPath ? "./assets/gameplay.mp4" : undefined, characterImageUrls: new Map(), speechUrls: new Map() } });
  assert.equal(composition.renderable, true); assert.deepEqual(composition.missingSpeechLineIds, []); assert.match(composition.html, /data-composition-id="fake-text-/); assert.match(composition.html, /data-timeline-label="Fake Text messages"/); assert.match(composition.html, /id="chat-panel"/); assert.match(composition.html, /height:1824px/); assert.match(composition.html, /const offsets=rows\.map/); assert.match(composition.html, /rows\.slice\(0,index\)/); assert.match(composition.html, />92</); assert.match(composition.html, /Jessica/); assert.match(composition.html, /A deterministic incoming message/); assert.match(composition.html, /timeline\.fromTo/); if (backgroundPath) assert.match(composition.html, /id="fake-text-gameplay"/);
  await writeFile(join(directory, "index.html"), composition.html);
  const { execFile } = await import("node:child_process"); const { promisify } = await import("node:util"); const cli = join(process.cwd(), "node_modules", "hyperframes", "bin", "hyperframes.mjs"); const checked = await promisify(execFile)(process.execPath, [cli, "check", directory, "--json", "--at", "0,1,3"], { timeout: 120_000, maxBuffer: 10 * 1024 * 1024 }); const report = JSON.parse(checked.stdout) as { summary?: { errors?: number } }; assert.equal(report.summary?.errors ?? 0, 0, checked.stdout);
  console.log(JSON.stringify({ ok: true, projectType: added.project.editorState.projectType, messages: fakeTextBlocks(added.project.editorState).length, durationSeconds: composition.durationSeconds, checkErrors: report.summary?.errors ?? 0, ...(keepArtifacts ? { artifactDirectory: directory } : {}) }, null, 2));
} finally { closeDatabase?.(); if (!keepArtifacts) await rm(directory, { recursive: true, force: true }); }
